### ISSUE TITLE
Unable to set fan speed

### ISSUE THREAD

**Issue by rayzorben** [mike-grant/haaska#101]
I have the Home Decorators Collection Gardinier fan, which works with Wink. From Home Assistant, it sees it as a fan, and I can control the speed with it.

However from Alexa/haaska I am unable to set the speed, I have tried
'set Rosemarys fan to low'
'set Rosemarys fan to 1'
'set Rosemarys fan to 50 percent'

Here is what discovery reports the fan as

```
{
          "capabilities": [
            {
              "interface": "Alexa.PowerController",
              "properties": {
                "proactivelyReported": true,
                "retrievable": true,
                "supported": [
                  {
                    "name": "powerState"
                  }
                ]
              },
              "type": "AlexaInterface",
              "version": "3"
            },
            {
              "interface": "Alexa.PercentageController",
              "properties": {
                "proactivelyReported": false,
                "retrievable": false,
                "supported": []
              },
              "type": "AlexaInterface",
              "version": "3"
            },
            {
              "interface": "Alexa.EndpointHealth",
              "properties": {
                "proactivelyReported": false,
                "retrievable": true,
                "supported": [
                  {
                    "name": "connectivity"
                  }
                ]
              },
              "type": "AlexaInterface",
              "version": "3"
            }
          ],
          "cookie": {},
          "description": "fan.rosemary",
          "displayCategories": [
            "OTHER"
          ],
          "endpointId": "fan#rosemary",
          "friendlyName": "Rosemarys Fan",
          "manufacturerName": "Home Assistant"
        },
```

**Comment by anthonylavado** [comment]
Just as a heads up - this isn’t something that Haaska can fix. We just pass along the information that Home Assistant provides. Think of it like a mirror - we just reflect one thing to another.

With that out of the way, I don’t believe that Alexa has a capability to natively understand what a “fan” is. There are two ways to report it. It can be a “range controller”, or a “percentage controller”. Here, it appears that Home Assistant is defaulting to report it as a “Percentage”, so there is specific phrasing to use.

Can you try the following?
“Alexa, set the Rosemary’s Fan to 50 percent”

**Note the exact phrasing is important. Set the <device name> to <number> percent.**

**Comment by rayzorben** [comment]
@anthonylavado Thanks, I tried that and it still doesn't work, it just says "I'm not quite sure what went wrong".

Is there any debugging I can see in the lambda function to see if / what data is getting passed when I say that command?

**Comment by anthonylavado** [comment]
I just checked the Home Assistant code, the relevant piece is here:
https://github.com/home-assistant/home-assistant/blob/5716d0aa1a625f707a85d4a79b2eaa26a4d5afb0/homeassistant/components/alexa/smart_home.py#L859-L869

Based on your discovery information, and this code, it appears that Home Assistant doesn’t list setting a percentage as being supported by your fan (hence the empty `supported: []` in your discovery results).

As mentioned before then, this is an issue on the Home Assistant side, and it requires some of the stuff around your fan integration (likely starting with the Wink module) to be updated. Sorry about that! :-(
