### ISSUE TITLE
assumed_state switch variable not available in Alexa app.

### ISSUE THREAD

**Issue by snorkrat** [mike-grant/haaska#105]
Background: I have a broadlink IR transmitter which I used to control my TV, amplifier, etc.  Because the remote controls in HA can also be controlled by a physical remote I use the assumed_state variable to give me two separate on/off buttons for each switch in HA.  Using the old (auchter) version of haaska this would show up in the Alexa app as two separate buttons, but since upgrading to this new version the assumed_state variable for switches is ignored and now in the Alexa app it is one switch that toggles either on or off. 

The difficulty here is that, for example, if the TV had been powered on by the alexa app, then off by the physical remote, the alexa app would still be at the "on" position, forcing me to turn it off then on again (my "off" option on the switch actually runs a script to turn my amplifier and other things off) otherwise this would only be a minor inconvenience).  Whereas before, because there were two separate buttons even if HA or Alexa thought it was at the off position, I could still tap the off button either in HA or the Alexa app.

Hope this makes sense!

I have attached a picture of what the controls used to look like in the Alexa App.

![on off alexa](https://user-images.githubusercontent.com/29180003/57944455-f6292b00-78ce-11e9-8146-401d6a99f080.jpg)

**Comment by anthonylavado** [comment]
Hey there @snorkrat!
Thank you for using Haaska.

This set of code essentially acts as a “relay”. It uses the same mechanism that Nabu Casa Cloud uses, and it only shows you what Home Assistant provides. It doesn’t actually do any different handling for different devices or responses.

For this reason, you should probably ask this question to Home Assistant directly. They have some steps to follow listed here: https://www.home-assistant.io/help/reporting_issues/

**Comment by snorkrat** [comment]
Thanks for the reply.  No problem at all, thanks for the info!
