### ISSUE TITLE
Analyse return from Alexa?

### ISSUE THREAD

**Issue by Swiftnesses** [mike-grant/haaska#106]
Hi Guys,

Previously, I used a device called Homey for my home automation. Their Alexa integration returned the processed speech input (which could then be used in 'flows' to build automations. Is this possible via Haaska? If the processed input could be output, it would be super powerful with HA + Node Red!

**Comment by anthonylavado** [comment]
Hi @Swiftnesses!
I don’t believe this would be possible with Haaska. The code is relatively simple: it takes your request, and sends that to Home Assistant. It doesn’t do anything else in the middle, it is just a simple relay that passes messages to your HA install.

Sorry about that!
