### ISSUE TITLE
Integration Future

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#109]
Though I have not tested it personally, it seems that both #104, and as of April, the Home Assistant docs, feature improved code examples (see [the raw docs](https://github.com/home-assistant/home-assistant.io/blob/611805a01a1257531ac4248242cf96a6394b3d48/source/_components/alexa.smart_home.markdown) or the [live ones](https://www.home-assistant.io/components/alexa.smart_home/)).

The Home Assistant docs now also include a full step by step guide (much the like one I wrote for the Wiki here), and include a link to a Gist with sample code (which, like #104, uses Environment Variables, and is simpler).

At this point, Haaska’s position remains the same as before - a link in that doc.  But now I think since the docs include a full guide, it’s likely that Haaska itself will see less traffic. In addition, starting this past December, most of my free GitHub time is also being taken up by another very large project. As a result, I’m not sure how much further I’ll continue here.

@mike-grant - I realize there’s probably a few hundred people or so who use this, but if it’s alright with you, after a year and a half, I’m going to start stepping back and slowly reduce my involvement. I’ll make sure there are issues for anything I can think of that are outstanding, so the community can take it on as needed.

**Comment by mikeage** [comment]
Thanks for your work! I too have replaced haaska with the snippet from 104, but haaska served me well for quite a while :-)
