### ISSUE TITLE
Documentation Tasks?

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#11]
I plan on trying to set up the V3 branch this weekend, and will be documenting my experience along the way.

Do you have any changes you're already planning for the documentation? I can submit a PR after I've worked on it a bit if you'd like.

**Comment by jeroenterheerdt** [comment]
I have taken a stab at improving documentation for the original haaska, see [my fork](https://github.com/jeroenterheerdt/haaska/blob/patch-1/README.md)

**Comment by anthonylavado** [comment]
@mike-grant From my (quick) testing so far, it looks like the V3 branch is good to go here. Would it be okay with you if I wrote up instructions to go in the repo’s wiki?

**Comment by mike-grant** [comment]
@anthonylavado that sounds great, i've done some work on the documentation in the v3 branch, mainly slimming them out a bit, pointing to the home assistant documentation where it makes more sense (and saves from having to duplicate information)

**Comment by anthonylavado** [comment]
@jeroenterheerdt On a review of the docs, is there a reason you had to run the `aws labda add-permission...` line? I just tried a test of the function without it, and it still seemed to work.

**Comment by jeroenterheerdt** [comment]
It seemed to solve some permission problem I was having.

**Comment by anthonylavado** [comment]
@jeroenterheerdt Was it similar to #20?

**Comment by jeroenterheerdt** [comment]
No, I cannot recall for sure bit it had something to do with the skill not being allowed to start the function

**Comment by anthonylavado** [comment]
Closing this in favour of a new discussion.
