### ISSUE TITLE
Alexa can't find devices. haaska setup was successful

### ISSUE THREAD

**Issue by aristosv** [mike-grant/haaska#113]
So I went through all the steps and got a successful test at the end.
`Execution result: succeeded`
So I asked Alexa to scan for new devices, but she said no devices were found. So I logged in from https://alexa.amazon.com and run device discovery again, but no luck.

I'm I missing something here?

**Comment by anthonylavado** [comment]
In the test, you should see a list of devices it detected at the end. Is anything there?

**Comment by aristosv** [comment]
This is the result

![2019-06-27 19_53_47-Lambda Management Console](https://user-images.githubusercontent.com/528302/60284892-57540d80-9915-11e9-8096-3f1f1cd65f47.png)

**Comment by aristosv** [comment]
oh sorry, I just noticed the scroll bar. Yes, all the devices are there. It's a huge file.

**Comment by aristosv** [comment]
But still, shouldn't Alexa find all these entities when I ask her to scan for new devices?

**Comment by anthonylavado** [comment]
@aristosv You're right, it should - which is why I'm puzzled as to what's happening...

**Comment by aristosv** [comment]
it was an issue with my router

**Comment by fets13** [comment]
@aristosv  What issue was that ?
Cause I manage to have the same issue

**Comment by aristosv** [comment]
It's been some time, I don't really remember, but I had stability issues. Some times it would work other it wouldn't. So I abandoned this solution. I'm just using Home Assistant Cloud now, and I'm also looking into ha-bridge https://github.com/bwssytems/ha-bridge
