### ISSUE TITLE
Have to ask Alexa twice for every action

### ISSUE THREAD

**Issue by alekseyn1** [mike-grant/haaska#120]
Hi all,

I have a weird behavior that I could not find the explanation for:
every time I ask Alexa to turn a device on or off it tells me that the device isn’t responding but if I ask Alexa again - all works perfectly. I always have to ask twice.

Any ideas on what could be wrong?

**Comment by lishan89uc** [comment]
Haha I have similar issue but only sometimes.

**Comment by mike-grant** [comment]
@alekseyn1 How long between invocations is there? E.g. is this the first time that the skill has been called for a few hours, or is it consistently like this?

**Comment by alekseyn1** [comment]
Thanks for your reply Mike, it seems to have stabilized itself. Will close the issue now.
