### ISSUE TITLE
Ignore Wemo devices during discovery

### ISSUE THREAD

**Issue by ohkeepa** [mike-grant/haaska#121]
Admittedly, I don't really understand how the haaska integration works... it's quite complicated... but it works!  I have a ton of wemo devices that I'd like to have Alexa never discover.  They all have "wemo" in the name if that is helpful.  Is there any way to modify haaska to have it make Alexa NOT discover any wemo devices when I "Forget All" then "Discover" again?

**Comment by Hydci** [comment]
You can try this
`alexa:
  smart_home:
    filter:
      exclude_entities:
        - switch.outside`


I prefer to work like that send only what I need
`alexa:
  smart_home:
    filter:
      include_entities:
        - light.kitchen
        - light.kitchen_left
    entity_config:
      light.kitchen:
        name: Custom Name for Alexa
        description: The light in the kitchen`

**Comment by ohkeepa** [comment]
Thanks for your reply.  I have already tried that, but it doesn't seem to prevent Alexa from discovering Wemo devices.  I'm thinking it must be discovering them some other way?

**Comment by ohkeepa** [comment]
I'm convinced that Alexa is discovering the Wemo devices via wifi or something.  I can completely shut down HA and disable remote access on my Wemo app, and it still finds the devices during Discovery.  I've read where if you've had the Wemo skill linked to Alexa at one point, and then remove it, it STILL discovers Wemo devices.  They recommended contacting Wemo support, which I did, and was of course useless.

So, here's where I'm at... does anyone have some sample code to get me started with programmatically removing devices from my Alexa account?  I can run that script daily, and it would solve all my problems.

**Comment by lishan89uc** [comment]
Oh I get it now. You want Wemo completely not get discover by wemo. From what i know that not possible however what you can do is after it is discovered you disable them and/or rename them something weird like wemodeskignore instead of desk. That way it won’t get voice activated.

**Comment by ohkeepa** [comment]
I've already tried the renaming thing.  All of my Wemo devices begin with the word "Wemo".  And, neither disabling nor "forget"ing the Wemos prevent them from coming back and enabled when a Discovery is performed again.

**Comment by mike-grant** [comment]
Unfortunately as you've said in your comments, this doesn't appear to be an issue with Haaska itself, but another skill. So i'm going to close this.
