### ISSUE TITLE
url??

### ISSUE THREAD

**Issue by djmerkley** [mike-grant/haaska#131]
I'm hoping someone can help me.  I am a complete novice at all of this.  I think the problem I am having is with the instructions that state:
 
"Add any url you'd like for the privacy notice, e.g. "https://myhass.example.com""
and
"In the URL section, add your remote Home Assistant URL (e.g. https://my-hass.example.com:8123)"

It could be something else, but this is where I suspect I went wrong. Error message below.  I'm just not sure what to put in for the two urls above?
{
  "errorMessage": "HTTPConnectionPool(host='hassio.local', port=8123): Max retries exceeded with url: /api/alexa/smart_home (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffbcac43e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))",
  "errorType": "ConnectionError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      111,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True)"
    ],
    [
      "/var/task/haaska.py",
      65,
      "post",
      "timeout=(None, read_timeout))"
    ],
    [
      "/var/task/requests/sessions.py",
      581,
      "post",
      "return self.request('POST', url, data=data, json=json, **kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      533,
      "request",
      "resp = self.send(prep, **send_kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      646,
      "send",
      "r = adapter.send(request, **kwargs)"
    ],
    [
      "/var/task/requests/adapters.py",
      516,
      "send",
      "raise ConnectionError(e, request=request)"
    ]
  ]
}

**Comment by magenbrot** [comment]
Hi,

the privacy note url is not relevant.

You'll need to be able to reach your Home Assistant installation from the "public" internet. You can do this for example by enabling port forwarding in your router and using a ddns provider.
There's more information in the HA documentation here: https://www.home-assistant.io/integrations/alexa.smart_home/

regards
Oli
