### ISSUE TITLE
Can't Use URLs ending in "a" "p" or "i".

### ISSUE THREAD

**Issue by shbatm** [mike-grant/haaska#138]
Trying to setup my new hass.example.casa domain name with HAASKA and I kept getting an error that hass.example.cas could not be reached. 

I think I narrowed it down to [Line 102](https://github.com/mike-grant/haaska/blob/28836213731e2d19deaebd496e0bb536d636bd38/haaska.py#L102). The rstrip command is indiscriminate and removes any "/" "a" "p" or "i" at the end of the url.

Workaround for now is to just capitalize the last letter.

**Comment by mikepflu** [comment]
UGH, this had me pulling my hair out for hours tonight.  I can confirm that using a URL ending in "a" caused problems for me.  Additionally, making the final "a" in my URL an "A" did in fact work around the problem.

**Comment by mike-grant** [comment]
Did #127 fix this for you?

**Comment by shbatm** [comment]
Have not tested yet, but looks like it should do the trick.
