### ISSUE TITLE
haaska test failed

### ISSUE THREAD

**Issue by master-kenobi** [mike-grant/haaska#14]
in my lambda haaska function, i created this test...

```
{
  "header": {
    "payloadVersion": "3",
    "namespace": "Alexa.ConnectedHome.Discovery",
    "name": "DiscoverAppliancesRequest"
  },
  "payload": {
    "accessToken": "1"
  }
}
```
When I run the test, the result is failed. This is in the error log...

```
'directive': KeyError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 1003, in event_handler
    directive = event['directive']
KeyError: 'directive'
```

Please help.

**Comment by anthonylavado** [comment]
You’re looking to create the test function on the actual Lambda page? This is the one where you can click a “Test” button?

If so, I have this working. I’ll check what I put in.

**Comment by master-kenobi** [comment]
yes, that's right. i was using this test for the v2 haaska by auchter

**Comment by anthonylavado** [comment]
Alright, here's what you want:
```{
  "directive": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover",
      "payloadVersion": "3",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
    },
    "payload": {
      "scope": {
        "type": "BearerToken",
        "token": "access-token-from-skill"
      }
    }
  }
}

**Comment by anthonylavado** [comment]
The test command is different because of the newer API.
This is exactly what I have, as entered, and it works for testing.

**Comment by master-kenobi** [comment]
thanks. the test succeeded.

p/s: you are missing { in your sample.
