### ISSUE TITLE
Test haaska, KO 

### ISSUE THREAD

**Issue by ivanaragom** [mike-grant/haaska#154]
I've erased everything three times, and I've followed the manual completely, but can't find the problem ...

The haaska test fails and displays this error.

Thanks in advance

{
  "errorMessage": "500 Server Error: Internal Server Error for url: https://xxxxxxxxx.duckdns.org:8123/api/alexa/smart_home",
  "errorType": "HTTPError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      111,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True)"
    ],
    [
      "/var/task/haaska.py",
      66,
      "post",
      "r.raise_for_status()"
    ],
    [
      "/var/task/requests/models.py",
      940,
      "raise_for_status",
      "raise HTTPError(http_error_msg, response=self)"
    ]
  ]
}

**Comment by mike-grant** [comment]
Have you set up the relevant parts in Home Assistant? The HTTP 500 status implies there is an issue with your Home Assistant set up.
