### ISSUE TITLE
Skill discovery ok, but no new devices found 

### ISSUE THREAD

**Issue by raidolo** [mike-grant/haaska#156]
Hi guys,

I have a strange issue... the skill works fine and I can see the discovery response in the Home Assistant API debug logs, so it looks like Alexa is sending the discovery request correctly to my HA instance, through HAASKA...
I've deleted a switch using the "forget" button in the web alexa app, but now it seems I'm not able to add it back, Alexa keep saying there are no new devices found...

Any hint?

Thanks in advance.

**Comment by freire-nuno** [comment]
Hi. I have exactly te same issue. One thing I noticed is that the metrics for my lambda (CloudWatchMetrics) only shows the invocations made by me with the "Test" feature. I was expecting to see cals from Alexa, but no.

**Comment by raidolo** [comment]
It's the filtering of the CloudWatch probably... I see the calls from alexa... It wouldn't be possible otherwise... 

I'VE SOLVED THE ISSUE: 
I've removed everything except the device I want to add and now it gets discovered.
It seems that HA sends too many devices, or there was a device Alexa doesn't like.

Here is an example of the filtering with just one entity...

```yaml
alexa:
  smart_home:
    filter:
      include_entities:
        - switch.lampada
      exclude_domains:
        - switch
        - input_boolean
        - input_number
        - light
        - media_player
        - climate
        - cover
        - scene
        - camera
        - group
        - automation
        - script
        - scene
        - sensor 
        - binary_sensor 

Now I have to add everything back step by step... 

Cheers

**Comment by freire-nuno** [comment]
I also managed to to get it working.
I've moved my lambda to another region us-east-1 (N. Virginia) and now it's working. Initially my lambda  was in Ireland (since i'm in Portugal), but for some reason it was not working Alexa didn't reached my lambda. After the move all the devices were found.

**Comment by raidolo** [comment]
@freire-nuno in my case the lambda function worked properly, I saw the response in the HA logs... the problem I think is the amount of devices sent. Just to understand, how many devices you have?

**Comment by freire-nuno** [comment]
I also have filters in place. Right now I have 33 devices, but before my filters I got all the sensors and automations from HA and didn't have those problems (I think it was around 70 devices).
My filters are a little bit different, the are including not excluding.
Example:
```
   filter:
      include_entities:
        - cover.window_upstairs_shutters

```

**Comment by raidolo** [comment]
Yeah exactly I did the same... works better

**Comment by ochlocracy** [comment]
The maximum number of endpoints that can be returned is 300. And the `Alexa.SceneController` has a recommendation of 12 or less scenes in a single response, but can support more.

I'm investigating a similar problem with the alexa integration in HA with `media_player`. If you can provide additional information from your discovery responses that break the discovery; I'd appreciate it. 

https://github.com/home-assistant/core/issues/34029

**Comment by raidolo** [comment]
@ochlocracy interesting... because I do have a Denon media player as well...

I'll put the discovery output in the other thread...

**Comment by raidolo** [comment]
I've done some other tests, I can confirm that removing ONLY the media_player in the alexa included domains did the trick, and the discovery worked fine.

**Comment by jbech-linaro** [comment]
> I also managed to to get it working.
> I've moved my lambda to another region us-east-1 (N. Virginia) and now it's working. Initially my lambda was in Ireland (since i'm in Portugal), but for some reason it was not working, Alexa didn't reached my lambda. After the move all the devices were found.

Indeed, happened to me aswell, moving to N Virginia seems to fix my issue (I had Europe initially).
