### ISSUE TITLE
climate domains not discovered

### ISSUE THREAD

**Issue by master-kenobi** [mike-grant/haaska#16]
Everything is discovered perfectly except my climate entities. Is this a bug?

Additionally, I have tried exposing my temperature sensors and to my surprise it was discovered successfully. However, I am not sure how to ask Alexa to read out the sensor value. Any suggestion?

**Comment by master-kenobi** [comment]
I also have few switches but using `display_categories: THERMOSTAT`. They were not discovered. However after I removed the display_categories tag, they were discovered successfully.

**Comment by anthonylavado** [comment]
@master-kenobi So under the way things are structured now, Haaska is simply a relay. It is up to Home Assistant to expose the correct information and devices up to the “cloud”.

That being said, the implementation in 0.62 isn’t complete, but it should have temperature sensors working (see https://github.com/home-assistant/home-assistant/pull/11930 for details).

I’ll try to look at how thermostats are working later.

**Comment by anthonylavado** [comment]
@master-kenobi Just quickly reviewing that PR again, it looks like “sensor” is a supported domain, but not “climate”. Again, I’ll still have to confirm how my Nest shows up. Have to do it after hours to avoid messing up Alexa for my family :)

**Comment by master-kenobi** [comment]
Again, really appreciate your efforts. I'm wondering how to make use of sensors in Alexa. It doesn't seem to do anything.

**Comment by anthonylavado** [comment]
@master-kenobi Sorry for the delay in replying, got side tracked with a few things. Right now, @bitglue confirms that Climate is not fully implemented. Only temperature sensors are (and even those are finicky).

See: https://github.com/auchter/haaska/pull/109#issuecomment-364598755

**Comment by master-kenobi** [comment]
Thanks. Sure, closing this issue.
