### ISSUE TITLE
problem "errorMessage": "Unable to import module 'lambda_function'"

### ISSUE THREAD

**Issue by jluc2808** [mike-grant/haaska#168]
hi, 
i follow the tuto https://www.lesalexiens.fr/tutoriels/tutoriel-piloter-home-assistant-a-la-voix-grace-a-alexa/
and create all  needed , the start Test : 
result is : "errorMessage": "Unable to import module 'lambda_function'"

i suspect the problem is when i download the last verson haaska_1.1.0.zip which seems generating problems with lambda_function.py 

within the download page i can't set (there is no field) Gestionnaire by haaska.event_handler

i surely miss something , but i need help to solve this problem. 

thanks

**Comment by jluc2808** [comment]
reply :  the tag to change event_handler is now in another place and dissociated from the the download buton , so i didn't saw that this field is inside
as soon as i could change to the right handler everything is working.

**Comment by PepperPhil** [comment]
> reply : the tag to change event_handler is now in another place and dissociated from the the download buton , so i didn't saw that this field is inside
> as soon as i could change to the right handler everything is working.

Where is it now?
