### ISSUE TITLE
TLDs longer than 3 letters get truncated, causing the request to fail

### ISSUE THREAD

**Issue by Kyle-Falconer** [mike-grant/haaska#182]
I've got a domain name that has a TLD with more than 3 characters and had the configuration fail because of it.

As an example config.json, as edited in the Lambda:
```
{
  "url": "https://hass.domainname.casa",
  "bearer_token": "(removed)",
  "debug": false,
  "ssl_verify": true,
  "ssl_client": []
}

```

The error message given in AWS Lambda when testing is this:

```
"HTTPSConnectionPool(host='hass.domainname.cas', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fddbc39bf98>: Failed to establish a new connection: [Errno -2] Name or service not known',))"
```

Note that the `host` value there was trimmed the TLD of `casa` down to `cas`.

After examining the source code for urllib3, I noticed that empty ports are permitted, so my workaround was to add a colon after the `url`, and this allowed the request to succeed.

I wanted to report this here in case others ran across this issue, though it really should be tracked down further and fixed in the source (probably urllib3). In the meantime, a condition could be added in this library to add a colon at the end of the URL if it's not present.

**Comment by spoolr** [comment]
This was fixed a few months ago, so you're not using the latest code.  haaska.ph function get_url() used rstrip("/api") which seems like it would remove the string, but actually removes all the characters, so domains like .ca, .casa, .app would find the trailing "a", "p", "i" removed until the first non matching character.  

Your colon workaround was clever!  Another workaround was to use capitals, which actually means #127 mostly fixes the problem but it would still fail if the url is uppercase.

#127 
#138

**Comment by Kyle-Falconer** [comment]
Great, thanks for letting me know. I'll update the lambda and report back.

**Comment by Kyle-Falconer** [comment]
@spoolr  I just uploaded the "haaska_1.1.0.zip" from the [1.1.0 release](https://github.com/mike-grant/haaska/releases/tag/1.1.0) and am observing the same failure:

```
HTTPSConnectionPool(host='hass.mydomainname.cas', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a36349048>: Failed to establish a new connection: [Errno -2] Name or service not known',)): ConnectionError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 111, in event_handler
    return ha.post('alexa/smart_home', event, wait=True)
  File "/var/task/haaska.py", line 65, in post
    timeout=(None, read_timeout))
  File "/var/task/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/task/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/task/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/var/task/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hass.mydomainname.cas', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3a36349048>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by spoolr** [comment]
Well that certainly explains why you got the wrong code in the first place.  There is no up-to-date bundled release.

You can just copy and paste haaska.py itself from here or just change the one line at fault:

>return url.rstrip("/api").rstrip("/")

to 
>return url.replace("/api", "").rstrip("/")
