### ISSUE TITLE
make test missing from repo

### ISSUE THREAD

**Issue by MACscr** [mike-grant/haaska#19]
Seems the test script is missing from your repo.

**Comment by anthonylavado** [comment]
Hi @MACscr, yes, we have to update this in the instructions. Right now, you can use some info from another issue to test on the Lambda function page:
https://github.com/mike-grant/haaska/issues/14#issuecomment-362925908

**Comment by arisonpl** [comment]
Hi, I used the suggested test function and I am getting:

```
START RequestId: 3b522ddb-1105-11e8-b01a-0774bda33c65 Version: $LATEST
module initialization error: [Errno 13] Permission denied: '/var/task/haaska.py'

END RequestId: 3b522ddb-1105-11e8-b01a-0774bda33c65
REPORT RequestId: 3b522ddb-1105-11e8-b01a-0774bda33c65	Duration: 301.92 ms	Billed Duration: 400 ms 	Memory Size: 128 MB	Max Memory Used: 21 MB	
module initialization error
[Errno 13] Permission denied: '/var/task/haaska.py'
```

I followed the guide carefully, and I'm stuck on that last step. I was able to add the skill, but my devices are not being discovered and as above the Lambda function doesn't work.

Any suggestions how to approach it? I created the zip file and uploaded it to AWS.

**Comment by anthonylavado** [comment]
@arisonpl Continuing this in another issue: https://github.com/mike-grant/haaska/issues/20

**Comment by anthonylavado** [comment]
This is partially fixed in a recent Wiki update.
It now mentions that if you have the AWS CLI and JQ, you can test by using `make discover`.

Next steps are to break out testing to a separate page, and list the various testing methods there (local, or in the Lambda console).

**Comment by anthonylavado** [comment]
Fixed in the latest Wiki update. There is finally a proper page to explain the two test options. 
See:
https://github.com/mike-grant/haaska/wiki/Testing-Haaska
