### ISSUE TITLE
Alexa's source device/microphone id?

### ISSUE THREAD

**Issue by SuRGeoNix** [mike-grant/haaska#199]
Hi,

Is is possible to process the same voice command (from different Alexa source device) for different HA device?
I know that Haaska does only the relay, but is this information going to HA API to be available for custom handling?

eg. Alexa, turn on kitchen lights
1) coming from Home 1 (HA processes for kitchen lights on Home 1)
2) coming from Home 2 (HA processes for kitchen lights on Home 2)

Thanks for your great code :)

John

**Comment by mike-grant** [comment]
The device ID should be getting sent to HomeAssistant.
