### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#20]
Continuing from https://github.com/mike-grant/haaska/issues/19#issuecomment-365412847.

@arisonpl Did you upload the correct haaska? It should have made a ZIP archive that has these files inside:
<img width="189" alt="screen shot 2018-02-14 at 1 20 43 am" src="https://user-images.githubusercontent.com/596194/36190318-7e4dee2a-1125-11e8-8c44-d7e117a04f12.png">

**Comment by arisonpl** [comment]
@anthonylavado thank you

I cloned this repository, compiled the function and uploaded the zip. Here how it looks on AWS
<img width="1199" alt="applicationframehost_2018-02-14_07-57-24" src="https://user-images.githubusercontent.com/10801314/36191348-ee8b6730-115c-11e8-9a9c-e6cfd5f451fa.png">

and the test function:
<img width="614" alt="chrome_2018-02-14_08-00-36" src="https://user-images.githubusercontent.com/10801314/36191389-2d520014-115d-11e8-841f-1e7506b682d9.png">

**Comment by anthonylavado** [comment]
@arisopl Okay, it's a permission issue on `haaska.py` before it's built. 

If you're using Linux/Mac OS, you'll want to do the following with a terminal, in the directory where haaska.py is located:

```
make clean
chmod 755 haaska.py
make
```

Once you've got a new ZIP, upload that in it's place.

If you're not using Linux/Mac OS, we'll want to look at the permissions/properties for the file and make sure it does not say "Read only" or anything like that.

**Comment by anthonylavado** [comment]
@arisonpl Thank you for bringing this to my attention. I realize the source of the issue now:

> I cloned this repository, compiled the function and uploaded the zip.

When you clone the repository, the files default to having permission 644, or:
Owner - Read, Write
Group - Read
Other - Read

When this gets built, it doesn't get changed, and is carried through to the ZIP. As a result, when Lambda goes to run the function, it doesn't have permission to execute it.

If you use "[Download ZIP](https://github.com/mike-grant/haaska/archive/master.zip)" instead, you get a file with the correct permissions, and you don't have to modify them yourself.

I'll make sure we call out that using "Download ZIP" is preferred in the instructions.

**Comment by arisonpl** [comment]
@anthonylavado - thank you, that worked 👍 

The test is now successful, all devices from my home assistant instance are fetched, but still not getting them in the Alexa app. Most probably, that's something totally different now.

**Comment by anthonylavado** [comment]
@arisonpl Awesome. Thank you for the heads up! We'll make an issue to get that fixed. I'll close this now.
