### ISSUE TITLE
Transferring long lived access token

### ISSUE THREAD

**Issue by olbasoil** [mike-grant/haaska#201]
I've been migrating my home assistant to a new server. Now it's time to get Haaska up and running again (Last installed 6 months ago and has always worked perfectly).
Rather than following the guide from a..z, can I simply install my long lived access token (I have a note of it as text, and could probably dig down in the old file system if it is non-text) and install it into my new server. I can see how to generate a new token, but not import an old one?

**Comment by mike-grant** [comment]
Unfortunately this is a question that is probably best asked on the Home Assistant forums, I don't really know if this is possible.

It's relatively simple to just generate a new one and update your configuration (config.json) in the Lambda editor.
