### ISSUE TITLE
Discover devices not working

### ISSUE THREAD

**Issue by dibyadip-das** [mike-grant/haaska#212]
Although I tested the lambda function and it works flawlessly but Alexa skill is not able to discover any devices. Any idea as to why this is working?

**Comment by giuseppefava** [comment]
same problem...

**Comment by iMicknl** [comment]
@dibyadip-das @giuseppefava I face the same issue. Did you already figure out the issue?

When I execute the request body that I took from the debug log, I get all my devices in the response..

**Comment by stackunderflows** [comment]
Same problem here. Testing the Lambda works as expected but Alexa can't find any new devices.

**Comment by iMicknl** [comment]
> Same problem here. Testing the Lambda works as expected but Alexa can't find any new devices.

Try it first with just a few entities included via Home Assistant config. It seems that they have a limit on the amount of device you can add per call.

**Comment by stackunderflows** [comment]
> > Same problem here. Testing the Lambda works as expected but Alexa can't find any new devices.
> 
> Try it first with just a few entities included via Home Assistant config. It seems that they have a limit on the amount of device you can add per call.

How do you limit the devices in HA config?

**Comment by actstorms** [comment]
I got i working with 

alexa:
  smart_home:
    filter:
      include_entities:
         - entites
