### ISSUE TITLE
Use Download ZIP/Ensure 'make' sets permissions

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#22]
As discovered in #20, if someone clones the repository, then the files (namely `haaska.py`) will have the wrong permissions.

Git creates files with rw-r--r-- (644), where Lambda needs permission to execute. In my testing, the default permissions included with a "download" of the file rwx-r-xr-x (755) seems to work.

I propose two solutions to this issue, that are not mutually exclusive.

1) Change the install docs to recommend using "Download ZIP" rather than cloning the repository.
This is the best/fastest change, that will ensure success for most people. The files will be downloaded with the correct permissions, and everything should work.

2) Change the makefile to set the correct permissions.
In the build step, we should add a `chmod` to ensure everything has the right permission before it gets zipped up.

**Comment by mike-grant** [comment]
Just chiming in my opinion, but I would favour prioritising alter the make function (I actually use docker to run the makefile but that's another story). But it might be worth making reference to Download Zip being the quickest option for the majority of people to get started with this project.

Thanks!

**Comment by anthonylavado** [comment]
@mike-grant I agree. I'll try to get this in tonight (still midday here on the east coast of Canada).

**Comment by anthonylavado** [comment]
In addition to https://github.com/mike-grant/haaska/pull/24, I’ve also made changes to the documentation. This should now be all resolved.
