### ISSUE TITLE
A/C recognised as thermostat 

### ISSUE THREAD

**Issue by chemelli** [mike-grant/haaska#223]
My AC, exposed via 2021.7.x version of HA is seen as a thermostat in Alexa app while it should be seen as A/C.

Simone

**Comment by chemelli74** [comment]
Any feedback on this issue ?

Thx in advance,

Simone

**Comment by mike-grant** [comment]
Unfortunately, Haaska only proxies the request to your home assistant setup. You'll need to raise a call on the home assistant repo to get this looked into.

**Comment by chemelli74** [comment]
I think you closed it a bit too quickly 😉

HA already recognize it as an a/c and I have all the settings available (mode, temp, ventilation) but on Alexa I can set only the temperature.

Simone

**Comment by chemelli74** [comment]
Double checked and in HA the entity has domain "climate" so should be correct.

Am I missing something ?

Simone

**Comment by chemelli74** [comment]
Can you please reconsider this issue ?

Thx,

Simone

**Comment by chemelli74** [comment]
Ping

**Comment by mike-grant** [comment]
Unfortunately, this is a still an issue that needs looking at in the HomeAssistant codebase, what gets sent to Alexa via Haaska, is generated within HomeAssistant itself.

**Comment by kiwipaulrob** [comment]
Any progress? Would be great to tell Alexa to change fan speed. In meantime will investigate setting up new fan entity...
