### ISSUE TITLE
HTTPError  "404 Client Error: Not Found for url: https://****:8123/api/alexa/smart_home",

### ISSUE THREAD

**Issue by alekvie** [mike-grant/haaska#23]
I'm not sure if this is the correct way to ask for help. I used a older version of haaska by you, mike-grant, and everything were working fine. However, when I added a switch to home assistant alexa stopped finding devices (and I could not control the other devices with alexa). Thus, I tried the new updated version and now I get a error when using the following test event. Furthermore, alexa does not find any devices.

```json
{
  "header": {
    "payloadVersion": "2",
    "namespace": "Alexa.ConnectedHome.Discovery",
    "name": "DiscoverAppliancesRequest",
    "messageId": "F8752B11-69BB-4246-B923-3BFB27C06C7D"
  },
  "payload": {
    "accessToken": "1"
  }
} 

Det error is as follows:

{
  "errorMessage": "404 Client Error: Not Found for url: https://***:8123/api/alexa/smart_home",
  "errorType": "HTTPError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      108,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True).json()"
    ],
    [
      "/var/task/haaska.py",
      62,
      "post",
      "r.raise_for_status()"
    ],
    [
      "/var/task/requests/models.py",
      935,
      "raise_for_status",
      "raise HTTPError(http_error_msg, response=self)"
    ]
  ]
}
```

**Comment by mike-grant** [comment]
What version of HomeAssistant are you currently using?

Thanks

**Comment by alekvie** [comment]
Thank you for your quick reply! I'm using Home Assistant 0.63.2 on Hassbian.

**Comment by TheJulianJES** [comment]
@alekvie Can you send your configuration of Home Assistant? (It requires the Smart Home configuration for this skill now: https://home-assistant.io/components/alexa/#smart-home)

**Comment by alekvie** [comment]
Thank you @TheJulianJES 

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: x
  longitude: x
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: 
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  api_password: 
  ssl_certificate: /etc/letsencrypt/live/fullchain.pem
  ssl_key: /etc/letsencrypt/live//privkey.pem
  server_port: 8123
  ip_ban_enabled: True
  login_attempts_threshold: 5
  base_url: x
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - sonos

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:
 
# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google


  
  # Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# add switches in the switches.yaml file.
switch: !include switches.yaml

media_player:
  - platform: kodi
    host: 192.168.1.49
    
device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: 

alexa:
  smart_home:
    filter:
      include_entities:
      - media_player.kodi

**Comment by alekvie** [comment]
Thank you @TheJulianJES 
[configuration.zip](https://github.com/mike-grant/haaska/files/1734020/configuration.zip)

**Comment by TheJulianJES** [comment]
You can even expose full domains to Alexa, if you want that:
```alexa:
  smart_home:
    filter:
      include_domains:
        - alert
        - automation
        - cover
        - fan
        - group
        - input_boolean
        - light
        - media_player
        - scene
        - script
        - switch```

Also, you should consider secrets (https://home-assistant.io/docs/configuration/secrets/) in Home Assistant, if you share your configuration more often (or just delete the password before sending it). Now if it is your real password in that configuration, you should change it.

**Comment by alekvie** [comment]
@TheJulianJES 

Not the real password, but thank you. I still have to write:
alexa:
  smart_home:

or can I exlude alexa? e.g.,: 
smart_home:

**Comment by TheJulianJES** [comment]
@alekvie You will have to write:
```
alexa:
  smart_home:
```
It is the smart home option in the Alexa component, so you will always need that in your configuration.

**Comment by alekvie** [comment]
@TheJulianJES, ok. So as long as I have the smart_home: option in my configuration file, the error is probably caused by something else?

**Comment by TheJulianJES** [comment]
@alekvie Well, I see that you also used v2 test event. Try using the new one:
```
{
  "directive": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover",
      "payloadVersion": "3",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
    },
    "payload": {
      "scope": {
        "type": "BearerToken",
        "token": "access-token-from-skill"
      }
    }
  }
}
```

**Comment by alekvie** [comment]
@TheJulianJES, suddenly it works - the test and to discover new devices.  Thank you so much for your help!
