### ISSUE TITLE
tts not working 

### ISSUE THREAD

**Issue by tekstein** [mike-grant/haaska#243]
Hello, I have sucessfully install done Haaska on my HA and everything works except one feature. The TTS feature. Below is the error message I get in the developer tools. Not sure if there was a step I missed to have the TTS portion work. I have listing all my system specs below. Please let me know if you need any additional information. Any help would be greatly appreciated

"Failed to call service notify.alexa_media_bedroom_echo_dot_2. Unknown error"

Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest

Version | core-2022.7.5
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64
Timezone | America/Chicago
Configuration Directory | /config

**Comment by mike-grant** [comment]
Hey, this appears to be relating to Alexa Media Player, you'll want to file this issue over on their [repo](https://github.com/custom-components/alexa_media_player)

**Comment by tekstein** [comment]
Thanks for the response. Will do.
