### ISSUE TITLE
500 Server Error: Internal Server Error for url: http://****:8123/api/alexa/smart_home

### ISSUE THREAD

**Issue by 2devnull** [mike-grant/haaska#25]
Not able to get past the Lambda test. 

HA: 0.64

```
START RequestId: 26 Version: $LATEST
[DEBUG]	2018-02-28T20:30:01.563Z	26	calling alexa/smart_home with {'header': {'payloadVersion': '2', 'namespace': 'Alexa.ConnectedHome.Discovery', 'name': 'DiscoverAppliancesRequest', 'messageId': 'F8'}, 'payload': {'accessToken': '1'}}
[DEBUG]	2018-02-28T20:30:01.565Z	26	Starting new HTTP connection (1): *****
[DEBUG]	2018-02-28T20:30:01.926Z	267	http://****:8123 "POST /api/alexa/smart_home HTTP/1.1" 500 141
500 Server Error: Internal Server Error for url: http://****:8123/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 108, in event_handler
    return ha.post('alexa/smart_home', event, wait=True).json()
  File "/var/task/haaska.py", line 62, in post
    r.raise_for_status()
  File "/var/task/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://***:8123/api/alexa/smart_home

END RequestId: 2
REPORT RequestId: 26	Duration: 381.95 ms	Billed Duration: 400 ms 	Memory Size: 128 MB	Max Memory Used: 29 MB	


500 Server Error: Internal Server Error for url: http://****:8123/api/alexa/smart_home: HTTPError
```

```alexa:
  smart_home:
    filter:
      include_domains:
        - alert
        - automation
        - cover
        - fan
        - group
        - input_boolean
        - light
        - media_player
        - scene
        - script
        - switch
```

```
Error handling request
3:31 PM components/alexa/smart_home.py (ERROR)
```

**Comment by anthonylavado** [comment]
Hey there @2devnull,
It looks like this might still be the old test. I really need to update that part and fix the documentation.

Can you try the test I specify in this comment?
https://github.com/mike-grant/haaska/issues/14#issuecomment-362925908

**Comment by 2devnull** [comment]
Ha....it worked!...man, pulling my hair out for a couple hours, double checking everything thrice....using Postman....yeah, doc could be updated to reflex some of the UI changes on AWS also.

Thanks for the quick help on this.

**Comment by anthonylavado** [comment]
@2devnull Yeah... It's been a busy previous few weeks. My goal is to break down the documentation into complete steps, screenshots included. That way you don't have to refer to another Amazon document, making changes as you go.

Thank you for letting me know it worked! Feel free to close this out if you're good to go.

**Comment by 2devnull** [comment]
That would be good...the only issue is keeping in sync with Amazon UI changes, they seem to update things frequently, well all cloud providers for that matter.

Anyway, thanks again and great work on this!
