### ISSUE TITLE
Everything shows Offline in Alexa App Smart Home --> Devices

### ISSUE THREAD

**Issue by 2devnull** [mike-grant/haaska#26]
Alexa app was able to discover devices, but all shows as Offline. What could be causing this?

**Comment by mike-grant** [comment]
What version of homeassistant are you running?

**Comment by 2devnull** [comment]
Hi,
0.64.0

**Comment by 2devnull** [comment]
I did discover again after restarting HA ans some things are working now. Will close and re-open if it becomes an issue.

Thanks.
