### ISSUE TITLE
[QUESTION] - Anyway to get push notifications to work?

### ISSUE THREAD

**Issue by 2devnull** [mike-grant/haaska#27]
Would like to know if anyone using this is able to get around sending text for Alexa to say? Trying to use the speakers in the echos/dots etc for text-to-speech.

**Comment by anthonylavado** [comment]
Hey @2devnull,
It works off of the Smart Home Skill Support that was built for Home Assistant Cloud. Basically, it HA Cloud can do it, Haaska can do it. There’s no other “new” features.

As far as I know, using the Echos/Dots for TTS is still the same as it was before. I’ve heard of people having them connected to a Raspberry Pi via Bluetooth or Aux Audio as a workaround though.
