### ISSUE TITLE
Task timed out after 3.00 seconds when testing Lambda

### ISSUE THREAD

**Issue by valphabet** [mike-grant/haaska#29]
Hey guys! First let me thank you for  your work!

I am quite a newbie with Alexa Skills and here's my issue: when testing the lambda I am having the message "Task timed out after 3.00 seconds" every time, whatever I try. It seems that nothing is actually happening in the back ground. 
The points where I am not sure are: 1) did not set a SSL for my endpoint (which is http://ipaddr:port/) as said [here](https://home-assistant.io/components/alexa/#smart-home) and 2) in the test I put `"token": "access-token-from-skill"` because well... I cannot find the token (I understand that is fetches it with the token URI provided).
I have triple checked everything else.
Sorry if I am missing something obvious but I am lost...
Thanks

**Comment by anthonylavado** [comment]
@valphabet Did you use the test seen here?
https://github.com/mike-grant/haaska/issues/14#issuecomment-362925908

**Comment by valphabet** [comment]
yes @anthonylavado, I copied/pasted it directly

**Comment by valphabet** [comment]
Any ideas of things I can work on? :)

**Comment by valphabet** [comment]
solved. Had to set SSL.
