### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#3]
Hi @mike-grant! It looks like you’ve updated the code here to work with v3.

How’s the progress? Do you think it’s in a usable state?

**Comment by mike-grant** [comment]
Hi @anthonylavado So far i've only got the discovery part working with v3, but hopefully it won't take long to get the rest up to scratch!

**Comment by anthonylavado** [comment]
Thanks for the update. I’ve made a fork myself with the intention of learning Python along the way, and in the case that didn’t happen, to at least be a good repo maintainer as long as I can.

Since you’re doing some of the work (there also seems to be a version underway at @bryzka/haaska), that takes a load off me :)

I’d be happy to help maintain this and provide some front line support for users once it’s up and running.

**Comment by mike-grant** [comment]
Hey, thanks for the offer that would be most appreciated. At the moment i'm just prioritising what I would use with the skill e.g. Lights & Media Player. But any help in the future would be most appreciated!

Good luck with learning Python! This is my first python project too

**Comment by anthonylavado** [comment]
Lights and Media Player seem to be the favourite among people.

I’ll keep watching the project. Thanks for replying!
