### ISSUE TITLE
Assert payloadVersion ==3 / KeyError: 'directive'

### ISSUE THREAD

**Issue by fryguy04** [mike-grant/haaska#31]
Brand new to haaska, been figuring it out/configuring all day. I'm using Hassio so (to my knowledge) can't debug this issue much further (wish i could add print statements to 'smart_home.py' to see what is going on.

Basically I have Alexa + Lambda + Built-in Hassio Alexa web service communicating but getting the following error ....

```
2018-03-25 19:14:23 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 310, in _handle
.............
  File "/usr/lib/python3.6/site-packages/homeassistant/components/alexa/smart_home.py", line 624, in post
    hass, self.smart_home_config, message)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/alexa/smart_home.py", line 632, in async_handle_message
    assert message[API_DIRECTIVE][API_HEADER]['payloadVersion'] == '3'
KeyError: 'directive'
```

I get the above Error in "home-assistant.log" when I "Discover Devices" from my iPhone/Alexa App.

Which appears to me like haaska/lambda is sending some other `payloadVersion` than expected '3' (in Home Assistant's Alexa code ... I could be wrong, like i said, newb here)

When i do a Lambda `Configure Test Event` and give it the following:

```{
  "directive": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover",
      "payloadVersion": "3",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
    },
    "payload": {
      "scope": {
        "type": "BearerToken",
        "token": "access-token-from-skill"
      }
    }
  }
}
```

I do see (in Lambda "Function Code" "Execution Results" all my Hassio devices so I think I'm REALLY Close ... is this a known bug or anyone have ideas how to solve?  Thanks in advance

**Comment by trisk** [comment]
The test is written for v3, but your skill may still be configured to use the v2 API.

**Comment by mike-grant** [comment]
@fryguy04 did @trisk 's advice sort this for you?

**Comment by fryguy04** [comment]
YES! It now works. THANK YOU, i knew i was close ... simple radio button. I've taken a screenshot in case this helps anyone else.

![image](https://user-images.githubusercontent.com/3722912/38346297-1a181368-3862-11e8-9762-b0722a29e5ed.png)
