### ISSUE TITLE
"Climate" not recognized

### ISSUE THREAD

**Issue by kdjordjev** [mike-grant/haaska#33]
Hello
New to haaska but i was able to set it up and seems to be working more or less. 

Hass.io: 0.65.6
haaska: 0.4
**Working**: Scripts, Scenes, Automation, switches, media players, TV
**Not Working**: Climate

I am having troubles with my climate control. Hasska does not see any climate at all during the discovery session tested directly through Lambda.

I have (2GIG / Zwave). thermostat. I added a manual thermostat. Both of them are not detected by haaska.

I do not get any errors in the logs. 

Anyone having the same problem?
Do we have any steps i can take for debugging?

Thanks.
K

Discovery directive: I get all my devices excluding all Climate.
{
  "directive": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover",
      "payloadVersion": "3",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
    },
    "payload": {
      "scope": {
        "type": "BearerToken",
        "token": "access-token-from-skill"
      }
    }
  }
}

**Comment by anthonylavado** [comment]
@kdjordjev Hey there,
Thanks for writing in. Haaska is only a "connector" for Home Assistant & Alexa, so it does the same things that HA Cloud can do.

That means that we don't control devices and discovery, we just connect whatever Home Assistant gives us. Right now, Home Assistant doesn't have Climate devices exposed to Alexa. There's an open pull request that is still being worked on, so it should appear in a later version. Once it does, you'll need to update your install, then just ask Alexa to discover new devices. They should show up after that.

If you want to track the progress for adding Thermostats to Home Assistant/Alexa:
https://github.com/home-assistant/home-assistant/pull/13340

**Comment by kdjordjev** [comment]
thank you for being so responsive..
still trying to figure my way around :)
closing the issue
