### ISSUE TITLE
Not able to discover any devices

### ISSUE THREAD

**Issue by jwhite** [mike-grant/haaska#35]
When I test the lambda function I get this as a result that seems like its working fine....

`{
  "event": {
    "header": {
      "messageId": "364b3dde-c85f-4349-9408-19f6f2802e39",
      "name": "Discover.Response",
      "namespace": "Alexa.Discovery",
      "payloadVersion": "3"
    },
    "payload": {
      "endpoints": [
        {
          "additionalApplianceDetails": {},
          "capabilities": [
            {
              "interface": "Alexa.PowerController",
              "properties": {
                "proactivelyReported": false,
                "retrievable": true,
                "supported": [
                  {
                    "name": "powerState"
                  }
                ]
              },
              "type": "AlexaInterface",
              "version": "3"
            }
          ],
          "description": "group.upstairs",
          "displayCategories": [
            "OTHER"
          ],
          "endpointId": "group#upstairs",
          "friendlyName": "Upstairs",
          "manufacturerName": "Home Assistant"
        },
        {
          "additionalApplianceDetails": {},
          "capabilities": [
            {
              "interface": "Alexa.PowerController",
              "properties": {
                "proactivelyReported": false,
                "retrievable": true,
                "supported": [
                  {
                    "name": "powerState"
                  }
                ]
              },
              "type": "AlexaInterface",
              "version": "3"
            }
          ],
          "description": "group.downstairs",
          "displayCategories": [
            "OTHER"
          ],
          "endpointId": "group#downstairs",
          "friendlyName": "Downstairs",
          "manufacturerName": "Home Assistant"
        },
        {
          "additionalApplianceDetails": {},
          "capabilities": [
            {
              "interface": "Alexa.PowerController",
              "properties": {
                "proactivelyReported": false,
                "retrievable": true,
                "supported": [
                  {
                    "name": "powerState"
                  }
                ]
              },
              "type": "AlexaInterface",
              "version": "3"
            }
          ],
          "description": "switch.bedroom_lamp_1",
          "displayCategories": [
            "SWITCH"
          ],
          "endpointId": "switch#bedroom_lamp_1",
          "friendlyName": "Bedroom Lamp 1",
          "manufacturerName": "Home Assistant"
        },
        {
          "additionalApplianceDetails": {},
          "capabilities": [
            {
              "interface": "Alexa.PowerController",
              "properties": {
                "proactivelyReported": false,
                "retrievable": true,
                "supported": [
                  {
                    "name": "powerState"
                  }
                ]
              },
              "type": "AlexaInterface",
              "version": "3"
            }
          ],
          "description": "switch.bedroom_lamp_2",
          "displayCategories": [
            "SWITCH"
          ],
          "endpointId": "switch#bedroom_lamp_2",
          "friendlyName": "Bedroom Lamp 2",
          "manufacturerName": "Home Assistant"
        },
        {
          "additionalApplianceDetails": {},
          "capabilities": [
            {
              "interface": "Alexa.PowerController",
              "properties": {
                "proactivelyReported": false,
                "retrievable": true,
                "supported": [
                  {
                    "name": "powerState"
                  }
                ]
              },
              "type": "AlexaInterface",
              "version": "3"
            }
          ],
          "description": "group.all_switches",
          "displayCategories": [
            "OTHER"
          ],
          "endpointId": "group#all_switches",
          "friendlyName": "all switches",
          "manufacturerName": "Home Assistant"
        },
        {
          "additionalApplianceDetails": {},
          "capabilities": [
            {
              "interface": "Alexa.PowerController",
              "properties": {
                "proactivelyReported": false,
                "retrievable": true,
                "supported": [
                  {
                    "name": "powerState"
                  }
                ]
              },
              "type": "AlexaInterface",
              "version": "3"
            }
          ],
          "description": "switch.office_lamp_1",
          "displayCategories": [
            "SWITCH"
          ],
          "endpointId": "switch#office_lamp_1",
          "friendlyName": "Office Lamp 1",
          "manufacturerName": "Home Assistant"
        }
      ]
    }
  }
}`

I've linked the skill with my account successfully, but I don't seem to see the lambda function getting called when I initiate discovery on my phone.

How do I test this starting with the Alexa skill in the developer web page?  I am not sure how to narrow down the problem.

**Comment by jwhite** [comment]
Update - my issue was that my account was linked to the USA while my alexa was in New Zealand.

I needed to move the lambda from oregon to n. virginia otherwise it would not be called.

**Comment by anthonylavado** [comment]
@jwhite Thank you for the report! I'll keep it in mind for the documentation. Glad to hear it seems to be working now 😀

**Comment by rchl** [comment]
@anthonylavado I've spent last few hours trying to figure that same issue. Testing lambda completed successfully but skill wasn't calling the lambda function and there was no indication anywhere what could be wrong.
It would really help to note that in documentation.

**Comment by rchl** [comment]
And even though I've fixed it by creating Lambda function in N. Virgina (tried Ireland in Europe before), I still don't quite understand how is amazon determining which lambda should be called from the skill. I had default endpoint in skill defined to lambda in Ireland and that didn't work.

**Comment by anthonylavado** [comment]
@rchl - There is some mention of it in the [Amazon documentation](https://developer.amazon.com/docs/smarthome/steps-to-build-a-smart-home-skill.html) we link to though:

>>>Make sure you’ve selected:
- N.Virginia for English (US) or English (CA) skills
- EU (Ireland) region for English (UK), English (IN), German or French (FR) skills
- US West (Oregon) for Japanese and English (AU) skills.

The region is displayed in the upper right corner. Providing your Lambda function in the correct region prevents latency issues.
<<<

It’s a shame they don’t specify that you should choose based on the country your account is from, but I felt the language line made sense. 

You’re right, there is a refinement to the documentation that is long overdue. I will make a note to try and add a reference to this.

**Comment by rchl** [comment]
> It’s a shame they don’t specify that you should choose based on the country your account is from, but I felt the language line made sense.

Well, i'm not sure what my account's country is from in the first place. If that's the country selected in the profile then I have Norway selected there.

So I've created skill with English (UK) language added and lambda in Ireland (arn:aws:lambda:eu-west-1...) and that just doesn't discover any devices.

Skill was configured like that:
![skill](https://user-images.githubusercontent.com/153197/43529136-e4012368-95aa-11e8-9e29-b2e705df8bac.png)

So from that, I would assume that skill's language matches lambda region. But that didn't work at all.

I had to add lambda in US and select that as default endpoint (possibly setting it in US specific field would be enough). I just don't understand why is alexa assuming that for my account it should call US lambda. My account is not US, as far as I can tell.

**Comment by anthonylavado** [comment]
@rchl - So I've figured it out. It's not documented *anywhere* by Amazon, but the breakdown is this:

---

**EU (Ireland)**
- English (UK)
- English (IN)
- German
- French (FR)

**US West (Oregon)**
- Japanese
- English (AU)

**N. Virginia**
- English (US)
- English (CA) skills
- Rest of World / International Version

---

Since your Echo is the _International Version_ (purchased from Amazon.de), then it goes through the default North Virginia datacenter.

**Comment by anthonylavado** [comment]
@rchl It might also be the language set for your Alexa - whether you have it as English (US) or English (UK) seems to matter

**Comment by rchl** [comment]
@anthonylavado Well, I don't have Echo, I use Sonos devices to interact with Alexa, but in reality the device used shouldn't matter because this automation can be set up without any devices and tested on https://alexa.amazon.com/. So something in settings of alexa.amazon.com could affect the lambda called but I've just tried setting country to UK in both `Devices/This devices` and `Alexa Account/[User]'s Alexa Apps` and it's still calling US lambda.

Maybe it's detecting user's IP and deciding on its own? Since I'm in Norway, it decides to pick the "Rest of the world" region? Or maybe it just always defaults to US because it's hardcoded somewhere in Amazon's code? I don't know really.

**Comment by anthonylavado** [comment]
@rchl - Yeah, it's not something we set. If I had to guess, this time it's a limitation of the way Sonos implements it. It's all really a mess - there's no good documentation on it from Amazon.

What I'll do - in the Wiki, add a troubleshooting section, and suggest trying a local region first, and then the N. Virginia region if the others don't work.

**Comment by jaburges** [comment]
so i tried oregon - no dice (i'm in WA). rebuilt the lambda function in N.Virgina and devices discovered
