### ISSUE TITLE
Device no response

### ISSUE THREAD

**Issue by mcdull** [mike-grant/haaska#36]
I switched from auchter/haaska to this branch.  And updated the payload to v3.
I disabled and re-enabled the skill and linked again to my account. 
It successfully discover all my HA devices, but none of them response to the command.

"Echo, turn off the door light"
   "Door light is not responding"
"Echo, turn off the homeAC"
    "HomeAc is not responding"

**Comment by anthonylavado** [comment]
@mcdull Hrm... that’s really strange. If it can discover your devices, then that means that the link responded at least once between Amazon and your server.

I know the Alexa Voice Service has a really aggressive timeout - I think if it doesn’t get a response within 5 seconds, it just stops. I’ll have to look this up.

Are you able to try running the test on the Lambda page? I think we have instructions in the Wiki.

**Comment by anthonylavado** [comment]
@mcdull Alright, not the best instructions (I really need to update the documentation), but let me know if you can follow what we did in this issue:

https://github.com/mike-grant/haaska/issues/14#issuecomment-362925908

**Comment by mcdull** [comment]
@anthonylavado 
After revisit a bit, the discover function seems remembered old discovered device, so I tried delete all of them and since then, no device is being discovered.  All in all, I found that even using this branch, I still cannot choose the v3 payload or the link account will not be successful.  When I switched back from v3 to v2, link successful but still no devices discovered.  BTW, are there are config that I should do on the HA side beside adding 
alexa:
??

**Comment by anthonylavado** [comment]
@mcdull Ah! That would do it :smiley: 

Is it responding now?

**Comment by mcdull** [comment]
Yup. Discovery works and have response. Thank you for your help.

**Comment by mcdull** [comment]
@anthonylavado 
May I know if this skill support color temperature changing?
My light works fine in HA, but it takes no order from Alexa to change color temperature.  Alexa says "okay" but nothing changed.

**Comment by trisk** [comment]
@mcdull All of the Smart Home API support is in Home Assistant itself (the `alexa` component), not the skill. It should work if your light supports the `color_temp` and `min/max_mireds` attributes, but also check your HA logs.
