### ISSUE TITLE
SSL certificate needed?

### ISSUE THREAD

**Issue by fotiDim** [mike-grant/haaska#38]
Does this adapter require to setup an SSL certificate on our local installation or does it use websockets like the HASS cloud?

**Comment by anthonylavado** [comment]
@fotiDim Hi there, thanks for checking out Haaska.

It doesn’t require an SSL certificate, but it does require your Home Assistant install is reachable from the internet. For that reason, it’s best that you take every step possible to secure your Home Assistant install.

With HA Cloud, it opens its own secure connection outbound to the Alexa Voice Service.

Haaska goes the other direction, where when a command is sent from Alexa, it must go out and contact your local HA install.

Does that make sense?
Let me know if you have any questions or concerns.

**Comment by puppetcoder** [comment]
I didn't want to expose a home assistant endpoint so I used an SSH tunnel instead.  If anyone else is interested, I can parameterize this a bit and kick off a PR.

`def event_handler(event, context):
    config = Configuration('config.json')
    if config.debug:
        logger.setLevel(logging.DEBUG)
    ssh_key_pass = boto3.client('kms').decrypt(CiphertextBlob=b64decode(os.environ['ssh_key_pass']))['Plaintext']
    with SSHTunnelForwarder(
        ("myhomeassistantserver.com", 8124),
        ssh_username="homeassistant",
        ssh_pkey="./hass.key",
        ssh_private_key_password=ssh_key_pass,
        remote_bind_address=("0.0.0.0", 8123),
        local_bind_address=('0.0.0.0', 8123)
    ) as tunnel:
        ha = HomeAssistant(config)
        return ha.post('alexa/smart_home', event, wait=True).json()`

**Comment by anthonylavado** [comment]
@puppetcoder Wow! Anything is on the table, so if you want to make a PR, I’ll definitely review/merge.

**Comment by fotiDim** [comment]
@anthonylavado sure closing it and happy to test it out!
