### ISSUE TITLE
New Auth Providers

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#42]
According to the [Dev Blog](https://developers.home-assistant.io/blog/2018/07/02/trying-new-auth.html), new Auth Providers are going to be introduced in the future. This means that eventually the API Password that we use to communicate with HA's Smart Home v3 API will become a legacy feature.

In order to be supported by the new system, we will have to use OAuth2.

We'll have to look at how this can be implemented in the skill, in addition to allowing for automatic token refreshes.

**Comment by anthonylavado** [comment]
We'll need to watch this carefully:
https://github.com/home-assistant/home-assistant/issues/15703

**Comment by mike-grant** [comment]
I think that we will probably move to the long live token in the short term, it gives easier continuity for the project at the moment, as well as being simpler to implement in the short term.

home-assistant/home-assistant#15195

**Comment by balloob** [comment]
I haven't tested it, but the OAuth2 server in Home Assistant aims to be spec compliant, so you should be able to just point it at your instance for authentication. It will then call your lambda with a valid access token.

**Comment by mike-grant** [comment]
Thanks for that @balloob I'll take a more in depth look at it all this weekend.

**Comment by arigit** [comment]
The new auth system just went live. I haven't upgraded yet but per the hass blog post, while api_password can still be used, it generates a warning/notification. Just a heads up

**Comment by tommyjlong** [comment]
I'm still running 076.2 but using the new Auth and using legacy_api_password.  I just got Haaska up and running for the first time.  (THANKS FOR YOUR WORK ON THIS!!!!!).  
But did get the following in my HA log:
```
Log Details (WARNING)
Fri Aug 31 2018 14:32:26 GMT-0400 (Eastern Daylight Time)
Please change to use bearer token access /api/alexa/smart_home
```

**Comment by mike-grant** [comment]
Change has been merged into master.
