### ISSUE TITLE
can't get past this error when running test:  "errorMessage": "Unable to import module 'haaska'"

### ISSUE THREAD

**Issue by bbrendon** [mike-grant/haaska#43]
The AWS log is below. I deleted and recreated it a second time and got the same results.

The error listed first `  "errorMessage": "Unable to import module 'haaska'"`

detailed logs from amazon:
```
04:45:37 START RequestId: 66c3d855-93b3-11e8-8cad-910fc8f1f1de Version: $LATEST
04:45:37 Unable to import module 'haaska': No module named '_cffi_backend'
04:45:37 END RequestId: 66c3d855-93b3-11e8-8cad-910fc8f1f1de
04:45:37 REPORT RequestId: 66c3d855-93b3-11e8-8cad-910fc8f1f1de	Duration: 0.59 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 48 MB
04:51:33 START RequestId: 3b5da7db-93b4-11e8-a001-9f6dcd299493 Version: $LATEST
04:51:33 Unable to import module 'haaska': No module named '_cffi_backend'
04:51:33 END RequestId: 3b5da7db-93b4-11e8-a001-9f6dcd299493
04:51:33 REPORT RequestId: 3b5da7db-93b4-11e8-a001-9f6dcd299493	Duration: 4.25 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 48 MB
```

**Comment by anthonylavado** [comment]
@bbrendon Hey there! Just to be clear, you get this when trying to run the discovery test in the Lambda Console?

I’ll have a look at this later today (it’s really early here right now, EDT).

**Comment by bbrendon** [comment]
Yes, exactly. I was following the test console from this page.
https://github.com/mike-grant/haaska/wiki/Testing-Haaska

**Comment by anthonylavado** [comment]
@bbrendon It appears this might be related to the recent change to have an SSH Tunnel as an option. I’ve rolled that change back for now. Please re-download or re-clone the repository and try again.

**Comment by bbrendon** [comment]
That appears to have fixed it. The haaska.zip file was about 5mb before. Now its about 1mb.
