### ISSUE TITLE
Lambda Test Fail: Expecting Property Name Enclosed in Double Quotes

### ISSUE THREAD

**Issue by louisefindlay23** [mike-grant/haaska#46]
I ran the Lambda test but it ends up failing.

Response:
{
  "errorMessage": "Expecting property name enclosed in double quotes: line 5 column 1 (char 76)",
  "errorType": "JSONDecodeError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      103,
      "event_handler",
      "config = Configuration('config.json')"
    ],
    [
      "/var/task/haaska.py",
      75,
      "__init__",
      "self._json = json.load(f)"
    ],
    [
      "/var/lang/lib/python3.6/json/__init__.py",
      299,
      "load",
      "parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)"
    ],
    [
      "/var/lang/lib/python3.6/json/__init__.py",
      354,
      "loads",
      "return _default_decoder.decode(s)"
    ],
    [
      "/var/lang/lib/python3.6/json/decoder.py",
      339,
      "decode",
      "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"
    ],
    [
      "/var/lang/lib/python3.6/json/decoder.py",
      355,
      "raw_decode",
      "obj, end = self.scan_once(s, idx)"
    ]
  ]
}

Request ID:
"4220bb83-aaf9-11e8-b59c-ff979af5e237"

Function Logs:
START RequestId: 4220bb83-aaf9-11e8-b59c-ff979af5e237 Version: $LATEST
Expecting property name enclosed in double quotes: line 5 column 1 (char 76): JSONDecodeError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 103, in event_handler
    config = Configuration('config.json')
  File "/var/task/haaska.py", line 75, in __init__
    self._json = json.load(f)
  File "/var/lang/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/var/lang/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/var/lang/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 1 (char 76)

END RequestId: 4220bb83-aaf9-11e8-b59c-ff979af5e237
REPORT RequestId: 4220bb83-aaf9-11e8-b59c-ff979af5e237	Duration: 4.73 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 30 MB

**Comment by anthonylavado** [comment]
@louisefindlay23
Hey there! 👋
Just to be sure, you’re using the test from this page?

https://github.com/mike-grant/haaska/wiki/Testing-Haaska

**Comment by louisefindlay23** [comment]
Yes, I am.

**Comment by mike-grant** [comment]
HI @louisefindlay23 can you post your config.json file? Make sure that you remove any personal information e.g. the values in url & password.

Thanks!

**Comment by zackcaussy** [comment]
Hello Mike,
I don't know if it is correct to contact on this page or not but I have issue with haaska, maybe you can help me?

I ran under 2 different problem, I use the haaska guide from the wanderer, and I managed to install all, but Alexa wouldn't work for some reason.... I am kind of newbie, and I don't know what to do as it can be challenging to learn a new language when you don't know anything about it.

Well here is my issue:

I tried the set location for Ireland for my program in lambda. I got one error.
I tried location set to North Virginia for my program in lambda too, and I got another error.

I am based in France, so I should use Ireland I know but... it seems to be the same as louisefindlay23, which I guess you solved eventually.
So I post the first error maybe you will understand.

error:
{
  "errorMessage": "Expecting property name enclosed in double quotes: line 39 column 1 (char 865)",
  "errorType": "JSONDecodeError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      655,
      "event_handler",
      "config = Configuration('config.json')"
    ],
    [

2nd error on Ireland Amazon:
{
  "errorMessage": "'header'",
  "errorType": "KeyError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      660,
      "event_handler",
      "name = event['header']['name']"
    ]
  ]
}

For info I use Hassbian, but followed all steps from the wanderer's page. All went well, except the execution. The result, is I cannot even discover any device from Alexa.

I don't know if you can help of not, but if you can big thank you))
Have a nice day

**Comment by anthonylavado** [comment]
@zackcaussy Just to keep things separate, I’ve made a new issue for you. Please see #74.
