### ISSUE TITLE
Smart Home payload v2 works, v3 doesn't

### ISSUE THREAD

**Issue by mattmickeyj** [mike-grant/haaska#47]
Hi,

I have setup the skill and lambda function and all is working fine, however, I have to select v2 as the smart home payload and not v3 is that correct? 

![screen shot 2018-09-01 at 15 55 11](https://user-images.githubusercontent.com/24794869/44947112-00b69980-ae00-11e8-8c64-55b8941d6ab0.png)

Thanks,
Matt

**Comment by anthonylavado** [comment]
@mattmickeyj Hey there!
You have to use v3 for this skill.

Thanks!

**Comment by mattmickeyj** [comment]
I’d doesn’t work when I set the payload to v3 - only when it is set to v2.

**Comment by mike-grant** [comment]
@mattmickeyj as in the skill only responds when selecting the v2? You might have the wrong codebase if that's the case.

**Comment by mattmickeyj** [comment]
Yes, that’s correct. How’s the best way to check he codebase? Just re-clone the repository, create the zip and re-upload?

Thanks for getting back to me :)

**Comment by anthonylavado** [comment]
@mattmickeyj That’s one way to do it:
https://github.com/mike-grant/haaska

In the Wiki, I’ve also added a ZIP link. Maybe that will be easier?

Here it is:
https://github.com/mike-grant/haaska/archive/master.zip

**Comment by mattmickeyj** [comment]
Brill, thank you - that's now working :)  I must have messed something up somewhere along the way.
