### ISSUE TITLE
Security risk/opening ports needed?

### ISSUE THREAD

**Issue by starkillerOG** [mike-grant/haaska#48]
I have not yet tried haaska, but it looks very promising.
However it is unclear to me how my alexa echo dot communicates to HomeAssistant/Haaska.

- Does this communication happen locally on my home network between my echo dot and HA/Haaska, or does it communicate through Amazon’s servers on the internet?
- Do I have to expose my HomeAssistant to the internet in order for Haaska to work?
- Would I also need to open up ports on my router or is no configuration at the router side needed?
- How would I actually expose my HomeAssitant instance to the internet in a save way, knowing that I use samba share to edit my config files of HomeAssistant?

Sorry for all these questions, still getting to know Haaska and not still sure about the working.
I hope someone will be willing to help me and answer my (probably) dumb questions..

Thanks in advance!

**Comment by mike-grant** [comment]
Hi @starkillerOG 

- Does this communication happen locally on my home network between my echo dot and HA/Haaska, or does it communicate through Amazon’s servers on the internet? **Easy way to look at it, your echo dot will talk to Hasska which communicates with HomeAssistant for you**
- Do I have to expose my HomeAssistant to the internet in order for Haaska to work? **Yes, or Haaska will be unable to communicate with it. I believe the HA cloud way will save you having to open any ports, or make your HomeAssistant instance available externally.**
- Would I also need to open up ports on my router or is no configuration at the router side needed? **You would need to open a port up of some description, either by putting HomeAssistant behind a proxy, or simply opening the port to your HomeAssistant instance**
- How would I actually expose my HomeAssitant instance to the internet in a save way, knowing that I use samba share to edit my config files of HomeAssistant? **https://www.home-assistant.io/docs/configuration/securing/**

If you have any other questions, let me know!

**Comment by starkillerOG** [comment]
@mike-grant Thank you for your very very quick replay!
Very clear answers, thank you.

Not sure if I will take the risk of opening up HomeAssitant to the internet, really like keeping things as local as possible.

**Comment by mike-grant** [comment]
If you look at Home assistant cloud, your local instance makes the connection to the cloud so doesn't require opening ports up to the internet. Definitely worth a look [](https://www.nabucasa.com)
