### ISSUE TITLE
Contact and Motion Sensor API Update?

### ISSUE THREAD

**Issue by packetbrain** [mike-grant/haaska#49]
looking for a little direction here on whether you plant to or are even interested in adding features to Haaska as Amazon adds them... to plan ahead for my installations

I built door open/closed and deadbolt sensors integrated with HomeAssistant that this contact and motion sensor update API would "voice enable" with Alexa

https://developer.amazon.com/blogs/alexa/post/bda9d70c-2f0d-454d-9939-2eb82868cf35/announcing-contact-and-motion-sensor-apis-and-integration-into-alexa-routines-adding-new-home-automation-features-for-customers-and-new-opportunities-for-smart-home-developers

and

https://developer.amazon.com/docs/smarthome/state-reporting-for-a-smart-home-skill.html

And, of course, I'm happy to help with any beta testing if you do plan to add these capabilities to haaska
My HA config is here: https://github.com/packetbrain/HAConfig with the door/lock configs in sensor.yaml

Thanks for the work you have done!

**Comment by anthonylavado** [comment]
@packetbrain Hey! Thanks for opening this up.

The way Haaska works is like a relay - it just communicates with Home Assistant to send commands and receive messages from it. Haaska itself doesn’t actually support any device in particular - that all has to be done inside Home Assistant itself.

In order for this new device categories to be supported, I would recommend making the suggestion directly to Home Assistant. 

Unfortunately I’m not sure what’s the best method to do that.

**Comment by anthonylavado** [comment]
Looks like feature requests go here:
https://community.home-assistant.io/c/feature-requests

As Home Assistant is also a community driven and supported project, if someone is able to contribute, that helps make things go faster.

(Side note: I also realize I should make this distinction about Haaska/HA more prominent on the readme.)

**Comment by packetbrain** [comment]
ahhh yes, you are right!   I think I knew that way back when I first tested this interface

thanks for getting me closer to the solution... it seems that what I need may already be implemented here:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/alexa/smart_home.py 

under "class _AlexaLockController(_AlexaInterface):"
