### ISSUE TITLE
Can home assistant control smarthome devices?

### ISSUE THREAD

**Issue by adamf663** [mike-grant/haaska#50]
Is it possible for a home assistant script to reach out through alexa or whatever to control smart home devices?  
For example, I have a floor lamp that can be controlled by alexa or a phone app, but I want to be able to control it from home assistant.
It seems amazon has gone to extraordinary lengths to make smarthome devices operate one way only.

**Comment by anthonylavado** [comment]
Hi @adamf663!

There’s no native way that I know of to make commands “go to” Alexa services to control other items. This really makes sense if you consider that:
- each “service” or “skill” would need to be customized by the people who developed it
- this ensures that some new skill can’t interfere with other services

If the device you have can be controlled by Alexa, it’s probably got an API somewhere that you can tap in to. An interface to send/receive commands from.

That being said, Haaska is simply a relay - it’s the glue/bridge that connects Home Assistant to the Alexa Voice Service. It doesn’t add/remove any functions, and doesn’t control anything on its own.

I would recommend reaching out to the manufacturer of your device, and also asking in the Home Assistant forums for more assistance.

(Side note: what device are you trying to control? Maybe I can help look?)
