### ISSUE TITLE
build haaska using docker: no such option: --system

### ISSUE THREAD

**Issue by clarkewd** [mike-grant/haaska#52]
When using this command to build per the readme:

    docker build -t haaska . && docker run -v "$PWD":/usr/src/app haaska

I end up with:

	Successfully tagged haaska:latest
	mkdir -p build
	cp haaska.py config/config.json.sample config/config.json build
	pip install --system -t build requests

	Usage:
	  pip install [options] <requirement specifier> [package-index-options] ...
	  pip install [options] -r <requirements file> [package-index-options] ...
	  pip install [options] [-e] <vcs project url> ...
	  pip install [options] [-e] <local project path> ...
	  pip install [options] <archive url/path> ...

	no such option: --system
	make: *** [haaska.zip] Error 2
	Makefile:16: recipe for target 'haaska.zip' failed

Any thoughts on what's going wrong? Thank you!

**Comment by anthonylavado** [comment]
@clarkewd Looks like you're running in to something as part of #37, but I don't use Docker so I'm not really sure. @mike-grant Any thoughts?

**Comment by duckpuppy** [comment]
Actually... I'm building this on Debian Stretch, and I get the `no such option: --system` error without using docker to build, just simply using `make deploy`.

`pip install --help` indeed shows `--user`, but no `--system`. This is from pip 18.0

**Comment by u1f35c** [comment]
It sounds like you're not using the Debian provided pip but instead have installed it yourself? python-pip on stretch is at 9.0.1-2 and shows the --system option for me.

**Comment by duckpuppy** [comment]
Possibly I've updated pip (with pip), but maybe the fix should be to check for the Debian special version of pip rather than just Debian so that people who stay up to date aren't broken.

**Comment by anthonylavado** [comment]
@duckpuppy This is a good thought - first time we've had this reported too. I'll at least put a note in the documentation, and we'll see if I get a chance to make any changes to the makefile.

**Comment by anthonylavado** [comment]
Closing in favour of #69.
