### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by kuradi** [mike-grant/haaska#54]
seems instructions are kinda outdated. Developer Console @ https://developer.amazon.com i dont have any "Apps & Services"... also its unclear how and where i should get bearer token. any help?

**Comment by Mikei386** [comment]
Having exactly the same problem. I wanted to install Haaska today but nope... The instructions are totally outdated an I have no idea how to install it.

**Comment by anthonylavado** [comment]
@kuradi I just checked this - it’s still there. Could you let me know what you see?

I did the following:
1. Go to https://developer.amazon.com
2. (on mobile at least) Clicked on the menu icon at the top left
3. Selected “Developer Console”, and signed in with my Amazon Developer account
4. Once logged in, I had an option on the screen for “Login with Amazon”

See:
![3435879b-edb1-4e96-914a-b62ee20362fe](https://user-images.githubusercontent.com/596194/46917779-b432b200-cf98-11e8-8c9d-52e710c83c21.png)

**Comment by anthonylavado** [comment]
@Mikei386 Hi Mike - could you let me know exactly what problem you’re running in to? Is the same as above, or is there another issue?

Thanks :)

**Comment by anthonylavado** [comment]
@Mikei386 Thanks for letting me know. I’ll have to look through everything from start to finish again. After you set up Haaska once, you really don’t have to touch it again.

For a Long Lived Token, go to the Profile page in Home Assistant.

1. Sign in to Home Assistant, and go to the profile page
- You can do this by clicking your account name st the top left in the menu
- You can also go to http://YourHASSUrl:8123/profile
2. Scroll down to the bottom of the page, and under “Long Lived Access Tolen”, select “Create Token”
3. Give it a name, like Haaska. Click Ok, then copy the token shown to the config file. Make sure you put it inside the quotes.

**Comment by Mikei386** [comment]
Ahhh Thanks a lot.

Now my Lambda-Function is working and I can see my Home Assistant devices in the output log.

Now I only have to find out why the Alexa app with my skill enabled doesn't see any of my devices...
Will have to go through every step of the configuration to see where my mistake is...

**Comment by anthonylavado** [comment]
@Mikei386 I don’t remember if I mentioned this when I wrote the instructions, but did you ask Alexa to “Discover your devices”?

**Comment by Mikei386** [comment]
I just redid everything and now it works perfectly! :-)
Thank so much for your help and fast response.

**Comment by TPD94** [comment]
> The GUI for creating an Alexa-Skill, as well as creating the Lambda-Function changed.

can you show me please where you added "Alexa Smart Home" as a skill on lamda? i seriously cannot find it.

**Comment by mcc05** [comment]
@TPD94 , just set it up and it works great, however your right the AWS pages have changed alot.

Once you have created your lamda function is now graphical, on the left hand side there is a list of "Add triggers" you will find "Alexa Smart Home" click it in, and then config at bottom of page

@Mikei386, thanks it great

**Comment by jumpkick** [comment]
@TPD94 only certain Amazon regions support the "Alexa Smart Home" trigger for Lamda functions...  i.e. I had to switch from US-East-2 (Ohio) to US-East-1 (N. Virgina), to get that trigger to appear in the Lamda...   When I say switch, I had to delete and recreate the lamda in the new location.

**Comment by anthonylavado** [comment]
Closing this in favour of a new issue to cover the updates.
