### ISSUE TITLE
AWS Region

### ISSUE THREAD

**Issue by benmprojects** [mike-grant/haaska#56]
Does it matter which region I use in AWS. Some guides same N. Virginia and others say the region in which your account is created. I have all my lambda working but Alexa cannot find any devices.

**Comment by anthonylavado** [comment]
@benmprojects - Hey there, does the test from the Lambda Console work?

Do you have
`alexa:
  smart-home:`

Configured as per https://www.home-assistant.io/components/alexa/#smart-home ?

**Comment by benmprojects** [comment]
Hi Anthony Thanks for the quick response. The test using the code provided in the wiki works and discovers all my items.

Yes i have exactly this. 

```
alexa:

  smart-home:
```

**Comment by benmprojects** [comment]
is this my function name which I need to modify in makefile from haaska?

`aws-serverless-repository-alexasmarthomeskilladapt-1N42XHDW2IERW`

**Comment by anthonylavado** [comment]
@benmprojects Sorry for the delay here - life got in the way. Where are you at now with installing this?

**Comment by benmprojects** [comment]
Hi Anthony,

I have solved it. It was indeed the region. In Au I needed to use the Oregon sever.
