### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by mike-grant** [mike-grant/haaska#6]
A list of controllers that i'm planning on implementing in the near future, if anyone has any others that they'd like implementing then just comment below and I'll look at adding them

- [x] PowerController
- [x] BrightnessController
- [x] PercentageController
- [x] ColorTemperatureController
- [ ] TemperatureSensor 
- [ ] ThermostatController

**Comment by eXtatic-GitHub** [comment]
Thanks Mike, looking forward to Climate control

**Comment by filcole** [comment]
Curtains control would be fantastic.

**Comment by anthonylavado** [comment]
PlaybackController might not be bad, probably get Speaker/StepSpeaker in the process

**Comment by jeroenterheerdt** [comment]
Does anyone know if Alexa currently supports alarm systems? I would love to be able to arm / disarm my alarm system that is exposed through HASS.

**Comment by anthonylavado** [comment]
@jeroenterheerdt It doesn't appear to be listed in the [Smart Home Skill](https://developer.amazon.com/docs/smarthome/understand-the-smart-home-skill-api.html#what-kind-of-devices-are-supported) docs. That being said, perhaps you could present it to the Alexa component as a switch? On = armed, off = disarmed?

**Comment by anthonylavado** [comment]
When checking the Pull Requests on [Home Assistant](https://github.com/home-assistant/home-assistant/pulls?utf8=%E2%9C%93&q=alexa) it looks like there's a lot more coming.


Specifically for reference, only up to https://github.com/home-assistant/home-assistant/pull/11930 made it in to 0.62, so the rest is coming in a future release.

So far I see:
- alert
- automation
- cover
- fan
- group
- input_boolean
- light
- lock
- media_player
- scene
- script
- switch
- http
- sensor

**Comment by jeroenterheerdt** [comment]
by the way, hove you guys been able to dim any hue lights through alexa? I have my hue lights as LIGHT... still Alexa says 'I'm not quite sure what went wrong'.

**Comment by mike-grant** [comment]
Closed as all actions are handled within home assistant
