### ISSUE TITLE
Lambda error with test

### ISSUE THREAD

**Issue by fripsy** [mike-grant/haaska#63]
I have this error in lambda:
Function result:

```
"errorMessage": "'header'",
  "errorType": "KeyError",
  "stackTrace": [
     [
       "/var/task/haaska.py",
       660,
       "event_handler",
       "name = event['header']['name']"
     ]
   ]
}
```
Log output:
```
START RequestId: ecb6a464-ddbd-11e8-830e-41eea83581b5 Version: $LATEST
'header': KeyError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 660, in event_handler
    name = event['header']['name']
KeyError: 'header'

END RequestId: ecb6a464-ddbd-11e8-830e-41eea83581b5
REPORT RequestId: ecb6a464-ddbd-11e8-830e-41eea83581b5	Duration: 10.01 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 32 MB	

```
This is my test event:
```
{
  "directive": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover",
      "payloadVersion": "2",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
    },
    "payload": {
      "scope": {
        "type": "BearerToken",
        "token": "access-token-from-skill"
      }
    }
  }
}
```
I tried both with payloadVersion 2 and 3, after changing that in the skill.
Here is my config.json:
```
{
  "url": "https://xxxxxxxxxx/api",
  "password": "xxxxxxxxxx",
  "ssl_verify": false,
  "expose_by_default": true,
  "exposed_domains": [
    "alert",
    "automation",
    "climate",
    "cover",
    "fan",
    "group",
    "input_boolean",
    "input_slider",
    "light",
    "lock",
    "media_player",
    "scene",
    "script",
    "switch"
  ],
  "entity_suffixes": {
    "alert": "",
    "automation": "",
    "climate": "",
    "cover": "",
    "fan": "",
    "group": "Group",
    "input_boolean": "",
    "input_slider": "",
    "light": "",
    "lock": "",
    "media_player": "",
    "scene": "Scene",
    "script": "",
    "switch": ""
  },
  "debug": true
}
```
Perhaps I should mention that my HA (0.81.2) is on https and port 44444
I don't have a clue as where I have to look to get this working...

Thanks.
Frank.

**Comment by fripsy** [comment]
I just ran make again (after deleting haaska.zip) and I noticed this error:
```
botocore 1.12.28 has requirement urllib3<1.24,>=1.20, but you'll have urllib3 1.24 which is incompatible.
appdaemon 3.0.2 has requirement aiohttp==2.3.10, but you'll have aiohttp 3.4.4 which is incompatible.
```
However the zip is created...

**Comment by fripsy** [comment]
Got as far as resolving the errors with AWS CLI, so I started the whole process again, uploaded the newly created haaska.zip, ran the test again and got the same error as in the first post...
But... the error indicated 'header' not found, so I adjusted the test event as follows:
```
{
    "header": {
      "namespace": "Alexa.ConnectedHome.Discovery",
      "name": "Discover",
      "payloadVersion": "2",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
    },
    "payload": {
      "scope": {
        "type": "BearerToken",
        "token": "access-token-from-skill"
      }
    }
}
```
Now my test suddenly turns green... but with an error:
```
START RequestId: 2a1d12de-ddce-11e8-9163-275a1e4dff99 Version: $LATEST
[DEBUG]	2018-11-01T12:03:37.452Z	2a1d12de-ddce-11e8-9163-275a1e4dff99	calling event handler for Discover, payload: {'scope': {'type': 'BearerToken', 'token': 'access-token-from-skill'}}
[DEBUG]	2018-11-01T12:03:37.452Z	2a1d12de-ddce-11e8-9163-275a1e4dff99	invoking Alexa.ConnectedHome.Discovery Discover
[ERROR]	2018-11-01T12:03:37.453Z	2a1d12de-ddce-11e8-9163-275a1e4dff99	handler failed unexpectedly
Traceback (most recent call last):
  File "/var/task/haaska.py", line 104, in invoke
    payload = operator.attrgetter(name)(self)()
AttributeError: 'Discovery' object has no attribute 'Discover'END RequestId: 2a1d12de-ddce-11e8-9163-275a1e4dff99
REPORT RequestId: 2a1d12de-ddce-11e8-9163-275a1e4dff99	Duration: 1.21 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 29 MB	
```
Tried with payloadVersion 2 and 3.

**Comment by anthonylavado** [comment]
@fripsy - Hey there! Just looking at some of the details... a lot of the configuration you’re using is from the older version of Haaska, which doesn’t work with version 3 (this version).

This one is definitely Payload Version 3, and the config doesn’t keep all of those entities anymore. You decide what devices go in through your Home Assistant `configuration.yaml` file.

While I haven’t fully updated my instructions yet, the [Wiki](https://github.com/mike-grant/haaska/wiki) should help somewhat.

**Comment by anthonylavado** [comment]
@frippy - If you don’t mind me asking, are you following instructions from a video or other website?
This will help me warn others that they may be using outdated instructions.

**Comment by fripsy** [comment]
Well, I got bits and pieces from here and there, this is what made it work:
`https://github.com/auchter/haaska/issues/81`
So I'm using the old version then?
Wait a minute... I think I downloaded the files from 'auchter'..., how can I check ?

**Comment by anthonylavado** [comment]
@fripsy - If you open the `Haaska.py` file that was part of the download, it will either say:
`#!/usr/bin/env python3.6`

Or 

`#!/usr/bin/env python2.7`

If it says 3.6, you’re using this new version. If it says 2.7, that’s the old version (which is no longer supported).

Sorry for the confusion. The original creator of Haaska no longer replied to any fixes we tried to submit, which is why we made this new, separate version.

**Comment by fripsy** [comment]
Yep, it's the old version.
Will start over with the new version (now I got the old version working).
Do you know if this will work with French language also?
I live in France and would like to impress my friends with Alexa doing "French".

**Comment by fripsy** [comment]
As far as the wiki goes, most of my errors are not in the wiki:
- installing the AWS CLI in a virtual environment
- access denied errors on AWS
- using the old version
Will install the whole thing again (new version this time) and report what I found.
Cheers.

**Comment by anthonylavado** [comment]
@fripsy - Yeah, using this one it is a lot easier to do French. That’s one benefit. This basically gives Alexa a list of devices, and Amazon takes care of the language for commands.

For the AWS CLI, it’s not *really* used. It’s there as an option because some people might have already had it, and it came from the old instructions. I think we’ll remove that part to make it easier. You can do everything from the website.

Regarding the access denied errors, that’s something I’m looking at.

Regarding using the old version, well, that’s harder. When you go to the HA website, we’re now the ones that are linked, but there’s no way to put a notice or flag up on the other project page, which is what I would have liked. I’ll have to put a big notice on our project’s front page, and in an issue template.

I’m looking at updating all this on the weekend.

Thanks for letting me know! :smile:

**Comment by fripsy** [comment]
Error with running make:
```
pip install --system -t build requests
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --system
```
My system is Ubuntu 16.04, so it adds `--system` as option, after deleting that in `Makefile`, make runs and creates the haaska.zip

**Comment by fripsy** [comment]
After uploading the new zip, changing the test event back as mentioned in the wiki, I got this:
```
{
  "errorMessage": "HTTPSConnectionPool(host='altirama.duckdns.org', port=49302): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))",
  "errorType": "SSLError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      109,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True).json()"
    ],
    [
      "/var/task/haaska.py",
      62,
      "post",
      "timeout=(None, read_timeout))"
    ],
    [
      "/var/task/requests/sessions.py",
      572,
      "post",
      "return self.request('POST', url, data=data, json=json, **kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      524,
      "request",
      "resp = self.send(prep, **send_kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      637,
      "send",
      "r = adapter.send(request, **kwargs)"
    ],
    [
      "/var/task/requests/adapters.py",
      514,
      "send",
      "raise SSLError(e, request=request)"
    ]
  ]
}
```
I guess I should change something in the config?

**Comment by fripsy** [comment]
I just ran `make discover`, this is the result:
```
{
  "errorMessage": "500 Server Error: Internal Server Error for url: https://xxxxxx:44444/api/alexa/smart_home",
  "errorType": "HTTPError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      109,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True).json()"
    ],
    [
      "/var/task/haaska.py",
      63,
      "post",
      "r.raise_for_status()"
    ],
    [
      "/var/task/requests/models.py",
      940,
      "raise_for_status",
      "raise HTTPError(http_error_msg, response=self)"
    ]
  ]
}
```
If I type the url into my browser I get:
`405: Method Not Allowed`
My guess is that this is coming from HA, not from AWS, but I don't have a clue where to look...

**Comment by fripsy** [comment]
It is not HA, I found this in the Apache error log:
`Nov  1 23:40:10 altirama hass[28210]: 2018-11-01 23:40:10 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 34.254.94.200`

**Comment by fripsy** [comment]
Finally SUCCESS !!!
Perhaps you should mention in the wiki one has to create a long_access_token in the HA profile and and copy this token in the "Bearer" field in the config.
Took me almost a day to figure that one out...

**Comment by fripsy** [comment]
@anthonylavado 
Yeah I know it has something to do with Alexa's location...
Physically the device is in France, it was originally registered in France, but since that didn't work I changed the registration to the UK, but it makes no difference...
Is there a way to find out which arn server the physical device is using?

**Comment by fripsy** [comment]
Just a related question:
Can I modify what Alexa answers? The standard "OK" or "D'accord" isn't really funny...

**Comment by anthonylavado** [comment]
@fripsy - I wish. I would love to do the same, but it is controlled by Amazon.

Some people prefer the shorter answers, unlike something like Siri, which gives longer answers and tries to be funny.

I guess they just wanted to keep it simple.
