### ISSUE TITLE
Error when testing Lambda

### ISSUE THREAD

**Issue by Nobodi99** [mike-grant/haaska#64]
SO I did everything I needed to do according to the setup page. But now I'm stuck testing the lambda function...

I get following error:

> {
  "errorMessage": "Expecting value: line 6 column 18 (char 316)",
  "errorType": "JSONDecodeError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      104,
      "event_handler",
      "config = Configuration('config.json')"
    ],
    [
      "/var/task/haaska.py",
      76,
      "__init__",
      "self._json = json.load(f)"
    ],
    [
      "/var/lang/lib/python3.6/json/__init__.py",
      299,
      "load",
      "parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)"
    ],
    [
      "/var/lang/lib/python3.6/json/__init__.py",
      354,
      "loads",
      "return _default_decoder.decode(s)"
    ],
    [
      "/var/lang/lib/python3.6/json/decoder.py",
      339,
      "decode",
      "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"
    ],
    [
      "/var/lang/lib/python3.6/json/decoder.py",
      357,
      "raw_decode",
      "raise JSONDecodeError(\"Expecting value\", s, err.value) from None"
    ]
  ]
}

For the test I just copied the example from the testing page here.
Tested it without filling in the token and with the token. Same error.

my config.json looks like this:

> 
{
  "url": "https://********.duckdns.org/api",
  "bearer_token": "here-is-a-token",
  "debug": false,
  "ssl_verify": true,
  "ssl_client": [cert.pem]
}

I  copied the certificate into the config folder. 

Is there anything I may ave done wrong here?

**Comment by anthonylavado** [comment]
@Nobodi99 - It seems like its not getting the response it expects. Have you configured Home Assistant as per the setup page?

See: https://www.home-assistant.io/components/alexa/#smart-home

**Comment by anthonylavado** [comment]
@Nobodi99 Thanks for your patience! I figured it out. You don't need to copy the certificate in to the config folder, and you don't need to add it to your `config.json`. It should look like:

```{
"url": "https://********.duckdns.org/api",
"bearer_token": "here-is-a-token",
"debug": false,
"ssl_verify": true,
"ssl_client": [cert.pem]
}

**Comment by anthonylavado** [comment]
@Nobodi99 Thanks for your patience! I figured it out. You don't need to copy the certificate in to the config folder, and you don't need to add it to your `config.json`. It should look like:

```json
{
"url": "https://********.duckdns.org/api",
"bearer_token": "here-is-a-token",
"debug": false,
"ssl_verify": true,
"ssl_client": []
}
```

**Comment by anthonylavado** [comment]
@Nobodi99 - Unfortunately I'm not the greatest with Python, so I'm actually not sure. I will dig into it later. The important thing is that it is working, and it is verifying that there is a secure connection regardless.

**Comment by anthonylavado** [comment]
@nobodi99 - Checked it. It is useful if you are using a self-signed/self-created certificate. Since most people are using Let's Encrypt, it's not necessary to specify a custom certificate. LE is already a trusted authority.
