### ISSUE TITLE
error when  running docker build xxx run yyy ,   under OSX

### ISSUE THREAD

**Issue by gnkarn** [mike-grant/haaska#65]
is build ok ( seams to , no errors), but when run is executed  there is a pip command error , this is the output:

how should i change the command to make it work ? ,, tks

```
iMacGusos10ext5~/Downloads/haaska-master$ docker build -t haaska . && docker run -v "$PWD":/usr/src/app haaska
Sending build context to Docker daemon 145.4kB
Step 1/6 : FROM python:3.6
---> 3e4c2972dc8d
Step 2/6 : RUN apt-get update && apt-get install -y jq zip && pip install awscli && apt-get clean && cd /var/lib/apt/lists && rm -fr Release Sources Packages && truncate -s 0 /var/log/*log
---> Using cache
---> 4ae644c82f70
Step 3/6 : RUN mkdir -p /usr/src/app
---> Using cache
---> d7145cfb289d
Step 4/6 : COPY . /usr/src/app
---> Using cache
---> a49b53727f0a
Step 5/6 : WORKDIR /usr/src/app
---> Using cache
---> 97555dd83cf9
Step 6/6 : CMD ["make"]
---> Using cache
---> 4d0c3f5f8971
Successfully built 4d0c3f5f8971
Successfully tagged haaska:latest
mkdir -p build
cp haaska.py config/config.json.sample config/config.json config/config.json_backup build
pip install --system -t build requests

Usage:
pip install [options] [package-index-options] ...
pip install [options] -r [package-index-options] ...
pip install [options] [-e] ...
pip install [options] [-e] ...
pip install [options] <archive url/path> ...

no such option: --system
```

**Comment by anthonylavado** [comment]
@gnkarn - Hey there! Open the makefile in a text editor (like TextEdit, or Atom) and look for this line:

`pip install --system -t build requests`

And make it:
`pip install -t build requests`

I think I’m going to have to take this bit out. It fixes some systems, but breaks others.

**Comment by anthonylavado** [comment]
Actually, sorry, there’s a different spot. Find this:
`PIP_EXTRA = --system`

And make it read:
`PIP_EXTRA =`

**Comment by gnkarn** [comment]
ok, will try that now , in the mean time , i just tried with make , and the error was
```
Collecting requests
  Could not fetch URL https://pypi.python.org/simple/requests/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement requests (from versions: )
No matching distribution found for requests
make: *** [haaska.zip] Error 1

```

probably something i have configured wrong on my mac?

thank you

**Comment by gnkarn** [comment]
it is working , now , will progress on the installation process .. tks

**Comment by anthonylavado** [comment]
@gnkarn I'm going to close this issue for now, but if you have any questions, just let me know.

As a side note to anyone interested, I've made a plan to resolve issues like this in #69.

**Comment by jackdh** [comment]
> it is working , now , will progress on the installation process .. tks

How did you resolve it?
