### ISSUE TITLE
there is no "lambda smart home trigger"  on amazon lambda config 

### ISSUE THREAD

**Issue by gnkarn** [mike-grant/haaska#66]
there is no element named smart home trigger , on the lambda function trigger   configuration section ,

the options are 
```

API Gateway
AWS IoT
CloudWatch Events
CloudWatch Logs
CodeCommit
Cognito Sync Trigger
DynamoDB
Kinesis
S3
SNS
SQS
```
 probably something changed on the amazon configuration page ?

**Comment by anthonylavado** [comment]
There’s a reason for this... let me find it

**Comment by anthonylavado** [comment]
Read 6.16 on this page: http://collingwood.me.uk/blog/index.php/hass-io-and-alexa/

Basically, you have the wrong location set for Lambda

**Comment by gnkarn** [comment]
good , thank you , im now on the testing step, but is too late , will continue tomorrow ..
