### ISSUE TITLE
Setup wiki page doesn't cover using bearer token at all

### ISSUE THREAD

**Issue by justin8** [mike-grant/haaska#67]
The current setup page [here](https://github.com/mike-grant/haaska/wiki/Setup) mentions the password field for the config, which is no longer there, and no longer works. It does not mention the bearer_token or that it should be a long-lived application token generated in HASS.

**Comment by anthonylavado** [comment]
@justin8 - Hey there. Thanks for mentioning this. Yes, I am in the process of updating the documentation. Amazon changed enough of the UI that it was a much bigger re-write than originally planned. I expect to have more up by end of tomorrow.

**Comment by anthonylavado** [comment]
By that I mean - I’m separate from the writer of the code here, just a collaborator who volunteered to handle issues/documentation. So when this update it hit, it was a surprise to me too. I am working on it though :smile:

**Comment by justin8** [comment]
Haha. Thanks for the super fast response. Good to know it's getting sorted. With enough googling of the various issues from version changes (I just went from 0.64 -> 0.82) I've managed to get everything working as before and move off the paid HA cloud stuff to haaska. so most of the instructions are ok, mostly just title changes for some sections and slightly different UIs on websites :)

**Comment by anthonylavado** [comment]
Starting to get this all updated. There are holdover outside instructions provided that reference the token, as well as a new page that does.
