### ISSUE TITLE
Prepare a Pre-Built Version

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#69]
In order to make installation of Haaska even easier than before, we should create a release with:
- a sample config file, named `config.json`
- a pre-built ZIP that users can download

The local build with make isn't needed in most cases, and as seen in some other issues, our usage of `pip` can introduce a lot of error, depending on how people's systems are set up. 

With a pre-built version, there's no need to do anything other than just edit the config.json, and once uploaded to Lambda, the user can do that with the inline code editor if needed.

This will help with user adoption, as we reduce errors, and don't require people to have a python build environment set up. If an issue is identified with a dependency (I believe this is just _Requests_), then we can always rebuild.

**Comment by gnkarn** [comment]
hey , anthony , by following your instructions i was able yo complete all config steps ( is very easy to get lost if don't follow the steps in exact order , as you have to leave open windows and came back later ,  anyway 

when testing i get this error 

404 Client Error: Not Found for url: https://mysite.duckdns.org/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
File "/var/task/haaska.py", line 109, in event_handler
return ha.post('alexa/smart_home', event, wait=True).json()
File "/var/task/haaska.py", line 63, in post
r.raise_for_status()
File "/var/task/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mysite.duckdns.org/api/alexa/smart_home

----
i suspect it has something to do that i have caddy proxy running on my network , and i should add a new address , something like 

https://mysite.duckdns.org/api/alexa/smart_home

??
thanks for your support .!

**Comment by gnkarn** [comment]
i have included the new path in the caddy configuration file , and now the error is 👍 
```

405 Client Error: Method Not Allowed for url: https://mysite.duckdns.org/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
File "/var/task/haaska.py", line 109, in event_handler
return ha.post('alexa/smart_home', event, wait=True).json()
File "/var/task/haaska.py", line 63, in post
r.raise_for_status()
File "/var/task/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://mysite.duckdns.org/api/alexa/smart_home

```

**Comment by duckpuppy** [comment]
I'm good with this, as long as editing the config using the console isn't a required step (I'd still rather run `make deploy` with an already edited config.json). I'm an automation guy, and I try to make things work such that I never log into the AWS console at all.

**Comment by anthonylavado** [comment]
@duckpuppy Yup! This would still be an option, the idea is to just have a release that can be downloaded if people so wish. Since it gets stored separately, it doesn't detract from your use at all :smile:

**Comment by zackcaussy** [comment]
Hello Anthony,

thank you very much for your nice work and dedication. I have a request, even though I follow all your steps for haaska, I'm still running into an error, maybe you can help.
I know i am not running Hassio but instead Hassbian, but things go smooth too. Expect at the end.
Here is my error, maybe someone is running into the same thing. 

I don't know if you can help or not, but that would be great, and you can even tell an user of Hassbian used your step by step command and manage to do it at the end.
Well finger's crossed, hope it will work.

here is my error:
{
  "errorMessage": "'header'",
  "errorType": "KeyError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      660,
      "event_handler",
      "name = event['header']['name']"
    ]
  ]

This is made after the installation and the first test at the end of this page here: (source)
http://collingwood.me.uk/blog/index.php/hass-io-and-alexa/

**Comment by timbiotic** [comment]
did this get created? I am having a terrible time trying to get makefile to run in my dockers or unraid server

**Comment by anthonylavado** [comment]
@timbiotic - Not yet. Coming later today :)

**Comment by anthonylavado** [comment]
This is now available here: 
https://github.com/mike-grant/haaska/releases/latest

@mike-grant Is it possible to remove the other releases? I realized that some of the issues we've had lately involved people using older builds, and removing the pre-ASK v3 versions should help reduce confusion.

**Comment by mike-grant** [comment]
@anthonylavado I'll have a look at if they can be hidden first, but I'll delete the releases if they can't be.
