### ISSUE TITLE
405 Client Error: Method Not Allowed

### ISSUE THREAD

**Issue by gnkarn** [mike-grant/haaska#70]
Still trying to make the configuration right ,
one doubt i have is how to configure my proxy to be sure the request is being send to the right url ,
up to this test  i added the following to my proxy config:

```
mysite.duckdns.org/api/alexa/ {
    proxy / myip:8123 {
        websocket
        transparent
    }
}  

mysite.duckdns.org/api/alexa/smart_home {
    proxy / myip:8123 {
        websocket
        transparent
    }
```

```
calling alexa/smart_home with {'header': {'messageId': 'xxx', 'name': 'TurnOnRequest', 'namespace': 'Alexa.ConnectedHome.Control', 'payloadVersion': '2'}, 'payload': {'accessToken': '1', 'appliance': {'additionalApplianceDetails': {}, 'applianceId': 'unique-id-for-non-dimmable-bulb-specific-to-user1'}}}
[DEBUG]	2018-11-05T17:40:15.768Z	xxxx	Starting new HTTPS connection (1): mysite.duckdns.org:443
/var/task/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[DEBUG]	2018-11-05T17:40:17.56Z	xxxx	https:/mysite.duckdns.org:443 "POST /api/alexa/smart_home HTTP/1.1" 405 23
405 Client Error: Method Not Allowed for url: https://mysite.duckdns.org/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 109, in event_handler
    return ha.post('alexa/smart_home', event, wait=True).json()
  File "/var/task/haaska.py", line 63, in post
    r.raise_for_status()
  File "/var/task/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://mysite.duckdns.org/api/alexa/smart_home

```

**Comment by gnkarn** [comment]
i found that the problem  is really the test example , the automatic test example is not correct for v3 ,
this one is   https://github.com/mike-grant/haaska/issues/14#issuecomment-362925908

will continue digging, but i have a green page now.

**Comment by gnkarn** [comment]
ok, i passed the lambda test , but after testing the lambda function and executing ok, how to make my eco dot , to recognise the new skill ??

**Comment by gnkarn** [comment]
it partially works , on the alexa mobile app , but have no way yet to enable it on the eco dot , and even when my skill is in spanish , and works fine on the app, my eco dot is still working in english, it seams the eco dot is not aware of the new skill .

is there any way , to get this ? 

on the app, the only skills working so far , are the ones related to on off switches and lights , is there a guide to make other controls included ?, like media players , automations, precedes etc?

 thank you

**Comment by anthonylavado** [comment]
@gnkarn - Hey there! I just got home from work, so I can answer -

There is no invocation name. This uses the native Smart Home skill, so you can say:
“Alexa, turn on kitchen light”
“Alexa, turn on all the lights”
“Alexa, set the kitchen light to blue”

And so on.

Just say Alexa, the name of your device, and what you want to do.

**Comment by gnkarn** [comment]
Hi , just got that part working , see my recent message , we cross ourselves

**Comment by gnkarn** [comment]
anthony , are you on discord ?

**Comment by gnkarn** [comment]
gave up on this , it seams that the echo dot , no mater what you do can not be changed to spanish, even if your app on the phone works perfectly in spanish , the other problem i see is , how to know what are the devices discovered by haaska , because the list i see in the app is too short compared with the devices i have ,  i think it is just  devices configured as lights or switches.
is there a way to make the rest to be recognised ?, 
on the test interface , i see many other devices , for example like

```
 "description": "media_player.samsungtv_living",
          "displayCategories": [
            "TV"
          ],
          "endpointId": "media_player#samsungtv_living",
          "friendlyName": "SamsungTV_living",
          "manufacturerName": "Home Assistant"
        },
        {
          "additionalApplianceDetails": {},
          "capabilities": [
            {
              "interface": "Alexa.PowerController",
              "properties": {
                "proactivelyReported": false,
                "retrievable": true,
                "supported": [
                  {
                    "name": "powerState"
                  }
                ]
              },
```
but , then they do not appear on the app, devices list .

**Comment by gnkarn** [comment]
so , i have unliked the skill from my account , then tried to link it again, but i cant now enable the skill again from my alexa app .. 

so , stuck in here now , went back two squares ..

**Comment by gnkarn** [comment]
deleted , the skill , made it again, linked to my account successfully run lambda ok , but no device is shown on the alexa app.

**Comment by fripsy** [comment]
@gnkarn 
The only way to get this to work when your Echo is not in the UK or the USA (like mine, I'm in France) is that you set your address in the UK everywhere (Echo, app, developer account).
The build your lambda function in N.Virginia.
In your skill put in the arn from N.Virginia as the default.
You add your language to the skill (in my case it was French), set your Echo to your language and voilà!
The drawback is that if you ask Alexa the weather, it will give you the weather in the UK...
To get a valid address in the UK, just type "valid uk address" in Google, I used the first result.
Just put that postal code in your Echo, app and developer account.

I spent several hours to figure this one out...

**Comment by gnkarn** [comment]
ok, will make a try,  for spanish  it says that the region should be eu ireland (?) ,  that is what i configured on the lambda function , so not sure i should go with spain or uk address  ? , it is all so convoluted ,  i don't know what the marketing guy was thinking when they developed this strategy ....

**Comment by gnkarn** [comment]
my lambda is  arn:aws:lambda:eu-west

**Comment by gnkarn** [comment]
absolutely no change at all , im guessing that , what is different is that the echo is different , there are versions with firmware and configuration for different regions , this one i bought in the US , and i think is limited to some type of configuration options . sound ridiculous i know  but are my conclusions so far ..

**Comment by gnkarn** [comment]
will check that tomorrow , thanks

**Comment by gnkarn** [comment]
after doing the changes you recommended , now Haaska works , but i was unable to change language on the echo dot , the same list is shown englishx3 , french,deutsch , jap, 

so i guess , language is also dependent on the echo device itself , there are versions for regions , ( crazy, but real) , thank you .
