### ISSUE TITLE
Documentation Tasks

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#78]
Here is a list of documentation tasks:

- [x] Update Wiki home page
- [x] Include a "Before You Begin" page with pre-requisites
- [x] Include a downloading and preparing page 

---

- [ ] Finish writing the Setup Page, with new instructions
- [ ] Write a new testing page
- [ ] Write a new using/how Haaska works page (this page should include an example configuration.yaml)
- [ ] Write a new Troubleshooting page
- [ ] Add screenshots as necessary
- [ ] Update the sidebar with the final list of pages

**Comment by optilude** [comment]
One thing to add: I don't think you actually document how to install the skill in the Alexa app. (It appears under "dev skills" but only if you are logged into the Alexa app with the same Amazon account used to create the skill)

**Comment by anthonylavado** [comment]
@optilude Fair point. It’s in the old usage section, which I haven’t updated yet. Will do so soon (hopefully).

**Comment by TheStig207** [comment]
@anthonylavado I just noticed that the scope in the Alexa Developer Console has to be "profile:user_id" just "profile" did not work for me. Maybe you can change this in the documentation ;)

**Comment by anthonylavado** [comment]
@TheStig207 Sorry, I no longer maintain haaska, and I've removed myself from commit access. The official Home Assistant docs have sufficient information to do a faster version of the integration: 
https://github.com/mike-grant/haaska/issues/109#issue-449226124
