### ISSUE TITLE
Question: Readme and skill-configuration still up to date?

### ISSUE THREAD

**Issue by Isstum** [mike-grant/haaska#8]
Hi there, thanks for your work!

I cant get my alexa skill working. I believe i followed every single step of the readme and the linked AWS tutorial. My skill shows up, i click on "Konto verknüpfen" (connect to account) and got ask to give permissions to access my profile. After that i only get an error message that something gone wrong and that i have to try it later.

I set up the skill multiple times but get the same error.

Any ideas?

**Comment by eXtatic-GitHub** [comment]
Can you show your App configuration in amazon developer (without  personal stuff)?

**Comment by Isstum** [comment]
I sorted it out! I made the same mistake as described here: https://stackoverflow.com/questions/47139882/using-amazon-oauth-for-alexa-skill-fails-to-link-the-skill-anything-specific-to

Maybe this problem should be addressed in the readme?

**Comment by anthonylavado** [comment]
Are you all working off the master branch, or the v3 branch?

The master branch isn't exactly up to date yet, and the v3 branch is where all the development is happening. It's being updated, and does have different instructions for set up.

**Comment by Isstum** [comment]
@anthonylavado Thats the stuff! 

Yes, i was working on master! Now i changed to v3 and it works! Awesome work!
The documentation seems to be up to date, first run -> success!

Thank you very much!

**Comment by anthonylavado** [comment]
@isstum Don't thank me, thank @mike-grant!

Like I said, the V3 branch is still being developed, so watch out as things may change.
