### ISSUE TITLE
Synology no make

### ISSUE THREAD

**Issue by Keltere** [mike-grant/haaska#83]
Hi sorry to bother but i've tried to follow the old guide but i can't use neither install make on my synology 214play.
Do you know if there is another way to do it?

**Comment by anthonylavado** [comment]
Hi @Keltere!
I'm sorry I haven't finished the new details yet. You can follow the short summary I've put here:
https://community.home-assistant.io/t/the-haaska-super-thread/76994/9?u=anthonylavado

Let me know if you have any questions.
