### ISSUE TITLE
Setting up Haaska is empty

### ISSUE THREAD

**Issue by TurboTronix** [mike-grant/haaska#84]
Was following your instructions which are great so far but now I've hit a blank. Literally the Setting up Haaska is a blank page :)

**Comment by crzg** [comment]
This was outlined in #78 

Anthony is clearly very busy - the above is not so much an issue, more of a bump and complaint which does not motivate contributers who put a good deal of effort into providing these tools for the rest of us, and it is already being worked on.

In the meantime, as outlined in the wiki itself, see below. 

_**ATTENTION**_
_The instructions are in the process of being updated. You can read them, but they may be incomplete._

_Until they are done, you can refer to [The Wanderer](http://collingwood.me.uk/blog/index.php/hass-io-and-alexa/) steps as well._

_Note that these instructions include steps for Hass.io, which may not apply to you. Skip that section if needed._

**Comment by anthonylavado** [comment]
@czrg - thanks for the reference. I don’t mind the comment though. Yes, I did get very busy with another repo that quite literally blew up in popularity. I am committed to still getting these done.

@Turbotronix - I’m happy to answer any questions you might have

**Comment by TurboTronix** [comment]
You did an amazing job, I haven't tried haaska yet but it looks promising.
Was just reading through the tutorial and wondered why it stopped (some
projects tend to just hit a dead end so thought that was the case).

I'm currently using node-red for my Alexa integration, will I be able to
create custom feedback from Alexa with haaska (ie have Alexa respond with
custom answers)? It's something node-red seems to lack in. Also will there
be the possibility of multi level questions? For instance with homeseer I
used a custom plugin where I could do something as follows:

Me: Alexa turn on TV
Alexa: what do you want to watch
Me: Netflix
Alexa: Ok

Once again keep up the great work!

**Comment by anthonylavado** [comment]
Okay, moving to the other issue you've opened, and closing this one for scope
