### ISSUE TITLE
Unable to import module 'haaska': No module named 'requests'

### ISSUE THREAD

**Issue by TurboTronix** [mike-grant/haaska#85]
When I tried the test code I got the following error:

{
  "errorMessage": "Unable to import module 'haaska'"
}

Log:
START RequestId: 6dcdb005-0b01-11e9-a333-91acb4a5fc89 Version: $LATEST
Unable to import module 'haaska': No module named 'requests'

END RequestId: 6dcdb005-0b01-11e9-a333-91acb4a5fc89
REPORT RequestId: 6dcdb005-0b01-11e9-a333-91acb4a5fc89	Duration: 13.01 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 21 MB	

Seems like I'm missing a requests library or something...

**Comment by anthonylavado** [comment]
@TurboTronix - I know this one! Use this ZIP:
https://github.com/mike-grant/haaska/releases/download/1.0.0/haaska.zip

And make the same edits that you would have to the config file.

This ZIP has all the modules you need built and ready to go, no more "make" required.

**Comment by anthonylavado** [comment]
Regarding your other question about multi-level responses, as it turns out, that isn't a thing that this skill can do.

There are a few different skill types, but the kinds relevant to this topic are a "smart home skill" (Haaska) and general custom skills based off intents (likely what Homeseer was using).

If you had to say "Alexa, tell Homeseer to..." or "Alexa, ask Homeseer to...", then it was intent based. 

Haaska works as a dedicated [Smart Home Skill](https://developer.amazon.com/docs/smarthome/understand-the-smart-home-skill-api.html). This means that you can just ask Alexa to do things, without specifying a name. In this case, you can just say "Alexa, turn on the kitchen light", and you don't have to say "Alexa, tell Home Assistant to turn on the kitchen light". It's a lot more natural.

You can still set up Intents with Home Assistant to have custom commands, if you'd like:
https://www.home-assistant.io/components/alexa/#i-want-to-build-custom-commands-to-use-with-echo

However, I've never used that function, so it would be best to ask a question on the Home Assistant forums for help with it.

**Comment by TurboTronix** [comment]
Quick question what are the benefits of using haaska instead of node-red?
Just wondering because I find node-red much simpler to get going.

**Comment by TurboTronix** [comment]
Ok cool I like node-red but I want to try this I've as well.

Figured out my issue in regards to requests. I just zipped the haaska
folder but we have to actually build it using make or docker.

Hard to find a reliable app that can do it well via Windows 10. I tried
PowerShell and cygwin. I finally managed to get PowerShell with docker to
creat the zip file but now when I tested it I got a timeout error...

Will need to see what it can be.

**Comment by anthonylavado** [comment]
If you use the ZIP I linked above, you don’t have to use make it docket at all. I already compiled it all, it just needs you to:
- unzip it
- make the changes to confit.json
- zip it again

**Comment by TurboTronix** [comment]
oh ok, so i'll redo the whole process and see if I can make it work.
Great work! Can't wait to test it out :)

**Comment by TurboTronix** [comment]
So I finally had some free time. I used your zipped file and now I get a diff error:

`{
  "errorMessage": "Invalid URL 'mypage.duckdns.org/api/alexa/smart_home': No schema supplied. Perhaps you meant http://mypage.duckdns.org/api/alexa/smart_home?",
  "errorType": "MissingSchema",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      109,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True).json()"
    ],
    [
      "/var/task/haaska.py",
      62,
      "post",
      "timeout=(None, read_timeout))"
    ],
    [
      "/var/task/requests/sessions.py",
      581,
      "post",
      "return self.request('POST', url, data=data, json=json, **kwargs)"
    ],
    [
      "/var/task/requests/sessions.py",
      519,
      "request",
      "prep = self.prepare_request(req)"
    ],
    [
      "/var/task/requests/sessions.py",
      462,
      "prepare_request",
      "hooks=merge_hooks(request.hooks, self.hooks),"
    ],
    [
      "/var/task/requests/models.py",
      313,
      "prepare",
      "self.prepare_url(url, params)"
    ],
    [
      "/var/task/requests/models.py",
      387,
      "prepare_url",
      "raise MissingSchema(error)"
    ]
  ]
}`

**Comment by TurboTronix** [comment]
Also when I type mypage.duckdns.org/api in chrome I get:

This site can’t be reached ronhome.duckdns.org refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by mike-grant** [comment]
You'll need your HomeAssistant installation to be available via the internet for Haaska to work. If you're getting refused to connect then it wouldn't appear to be available. Can you access it normally, e.g. without /api at the end?

**Comment by TurboTronix** [comment]
Yeah I've been using it all this time but without /api
Only when I add /api that it doesn't work.

**Comment by TurboTronix** [comment]
And I did port forward 443 into 8123

**Comment by mike-grant** [comment]
Do you have [this](https://www.home-assistant.io/components/alexa/#smart-home) section in your configuration?

**Comment by TurboTronix** [comment]
I have this:

api:
  alexa:
    smart_home:

**Comment by anthonylavado** [comment]
That’s good. That means it’s responding now.

When you use a web browser to access the page, it’s using a GET request, which isn’t allowed by the API. Instead, a POST request (which is what Haaska uses) works.

It should respond now.

**Comment by TurboTronix** [comment]
The thing is I see in hasska code it uses ronhome.duckdns.org/api/alexa/smart_home not https://ronhome.duckdns.org/api/alexa/smart_home

I get 405: Method Not Allowed when I use https://

when I don't use https:// i get:
This site can’t be reached ronhome.duckdns.org refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by TurboTronix** [comment]
OK fixed it by adding https:// in you config.json file

"url": "https://mypage.duckdns.org/api",

**Comment by TurboTronix** [comment]
OK it works now!! Thanks for helping me out! :)

**Comment by mike-grant** [comment]
Glad you got it working!

**Comment by canna051** [comment]
Hi guys,
I carefully followed the wiki guide step by step, starting again from scratch twice.
I always get the same error on the test:


END RequestId: dd407317-fed4-498f-b0fa-157e397405f1
REPORT RequestId: dd407317-fed4-498f-b0fa-157e397405f1	Duration: 0.38 ms	Billed Duration: 1 ms	Memory Size: 128 MB	Max Memory Used: 43 MB	Init Duration: 1.06 ms
`
{
  "errorMessage": "Unable to import module 'haaska'"
}

Function Logs
START RequestId: dd407317-fed4-498f-b0fa-157e397405f1 Version: $LATEST
Unable to import module 'haaska': No module named 'haaska'
`

I ensure that:
- my domain is accessible outside my network (on port 8123) with https:// 
- I put the right url in the config.json file on the zip file used.

More infos:
- If i surf to httpsblablabla:8123/api it says "404 page not found"
- if I surf to httpsblablabla:8123/api/alexa/smart_home it says "405: Method Not Allowed"

Hope this can help you to help me :P 
Thanks
