### ISSUE TITLE
Error when Testing

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#87]
Opening an issue for @itajackass, as per below issue comment. 

https://github.com/mike-grant/haaska/issues/58#issuecomment-451703902

**Comment by itajackass** [comment]
After a couple of try, with a router fritz box 7530,i get it working with appending 8123:

{
  "url": "https://xxx.duckdns.org:8123/api",
  "bearer_token": "yourtoken",
  "debug": false,
  "ssl_verify": true,
  "ssl_client": []
}

**Comment by anthonylavado** [comment]
Okay! This sounds good. Let us know if you need any help. Thanks for using haaska!
