### ISSUE TITLE
We were unable to link haaska at this time.

### ISSUE THREAD

**Issue by atideath** [mike-grant/haaska#89]
Hello.

I would like to use Haaska in my HA system but when I try to enable skill in my Alexa I get this message: "We were unable to link haaska at this time."

Where is the problem? How can I resolve it? Thanks!

**Comment by anthonylavado** [comment]
Hey there!
What does the error message look like? Is it like this?

https://m.imgur.com/gallery/HSpucjr

**Comment by anthonylavado** [comment]
Gonna close this now, but if you’re still having trouble, please let us know.
