### ISSUE TITLE
"errorMessage": "401

### ISSUE THREAD

**Issue by AngelofromTurin** [mike-grant/haaska#90]
hi, sorry for my bad english

im' sorry i try to read many issue and many instruction but not undarstand...
i'm using hass.io version 0.85.1
this the complete lambda's log:
Response:
{
  "errorMessage": "401 Client Error: Unauthorized for url: https://XXX.duckdns.org:8123/api/alexa/smart_home",
  "errorType": "HTTPError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      111,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True)"
    ],
    [
      "/var/task/haaska.py",
      66,
      "post",
      "r.raise_for_status()"
    ],
    [
      "/var/task/requests/models.py",
      940,
      "raise_for_status",
      "raise HTTPError(http_error_msg, response=self)"
    ]
  ]
}

Request ID:
"fa025e57-4e45-49cc-88dc-645c25c5fb8c"

Function Logs:
START RequestId: fa025e57-4e45-49cc-88dc-645c25c5fb8c Version: $LATEST
401 Client Error: Unauthorized for url: https://XXX.duckdns.org:8123/api/alexa/smart_home: HTTPError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 111, in event_handler
    return ha.post('alexa/smart_home', event, wait=True)
  File "/var/task/haaska.py", line 66, in post
    r.raise_for_status()
  File "/var/task/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://XXX.duckdns.org:8123/api/alexa/smart_home

END RequestId: fa025e57-4e45-49cc-88dc-645c25c5fb8c
REPORT RequestId: fa025e57-4e45-49cc-88dc-645c25c5fb8c	Duration: 757.56 ms	Billed Duration: 800 ms 	Memory Size: 128 MB	Max Memory Used: 29 MB	

hassio log:

INFO:2019-01-21 19:36:08,824:__main__:Requesting authorization
INFO:2019-01-21 19:36:08,825:__main__:34.245.188.147 - "POST /api/alexa/smart_home HTTP/1.1" 401 -

and this my config:

homeassistant:
  auth_providers:
   - type: legacy_api_password
   - type: homeassistant
   - type: trusted_networks
http:
  api_password: !secret http_password
  base_url: https://XXX.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
    - fd00::/8
api:
alexa:
  smart_home:
  endpoint: https://api.amazonalexa.com/v3/events
  client_id: !secret alexa_client_id
  client_secret: !secret alexa_client_secret

i tried to reupload the zip file, to change long the long life token, to review on for on the passage in amazon console...
Where is the bug?
thank you so much :)

**Comment by anthonylavado** [comment]
Hi @AngelofromTurin! 👋

If you go to `https://xxx.duckdns.org:8123/api/alexa/smart_home` (replace x with your domain), what does it say on screen?

**Comment by AngelofromTurin** [comment]
ok i change my forwarding rule now are correct and again the report of lambada is the first error 401 but if i try to connect at https://XXX.duckdns.org:8123 (the real one) 
the screen say: 405: Method Not Allowed
