### ISSUE TITLE
Voice code for Unlock/Disarm functionality

### ISSUE THREAD

**Issue by derry43** [mike-grant/haaska#93]
Thanks for the excellent work on this HA skill. I am really requesting a new feature in order to make use of the Lock/Unlock functionality. Alexa Smart Home skills do not appear to allow the Unlock feature without first requiring the user to set up a voice code of at least four digits before using that functionality.

https://developer.amazon.com/docs/custom-skills/security-testing-for-an-alexa-skill.html#cert-unlock

I cannot see any straightforward method for adding this functionality via the labmda management console or the alexa developer console. However after some digging around, I did find a nodejs example of a skill that implements a voice code (https://github.com/alexa/skill-sample-nodejs-salesforce).

Wondered if anyone was looking at  this functionality for haaska?

**Comment by anthonylavado** [comment]
Hey there! 👋 

Haaska is only a relay for Home Assistant. To put it another way, Home Assistant itself implements generates all the responses, and Haaska just connects that to your Alexa devices.

For example, we don’t actually implement any hardware/devices ourselves. When something gets enhanced or added for Alexa control, it all happens in the Home Assistant code. The request is probably best made there.

Another way to look at it: if you can do it with a Home Assistant Cloud, you can do it with Alexa.
