### ISSUE TITLE
new user

### ISSUE THREAD

**Issue by kentania** [mike-grant/haaska#95]
Buongiorno.
Perdonami ma sono un nuovo utente e l'ultima volta che ho programmato qualcosa è stato più di 20 anni fa a scuola. Ho tutto aggiornato con hassio 88.1. Mi da pero questo errore:

Good morning.
Forgive me but I'm a new user and the last time I planned something was more than 20 years ago at school. I have everything updated with hassio 88.1. This error gives me:
{
  "errorMessage": "2019-02-23T21:21:46.903Z 25353033-85fa-4059-90a8-51de9a331ecf Task timed out after 3.00 seconds"
}

Would you have any suggestions for how to solve the problem?

**Comment by anthonylavado** [comment]
Hey there, sorry for the delay in responding. This can happen if the connection from your Home Assistant server is really slow.

By default, AWS Lambda has a timeout of 3 seconds for any function call. You can extend this, but the maximum I would go with is the Alexa response timeout of 8s. Amazon/Alexa voice services are *very* strict about how long it takes for a response to be received. This is because anything too long makes Alexa seem too slow or unresponsive.

To increase the timeout:
* Log in to AWS, and go to Lambda
* Open your function (e.g. "haaska")
* Scroll down to the box labelled "Basic settings"
* Change the timeout to `0` min `8` sec

Try this and let me know if it works 😄

**Comment by kentania** [comment]
Intanto grazie mille per l'interessamento. Il tempo non è un problema, quando ho iniaziato ho capito subito che per me sarebbe stata una cosa lunga, anzi in questo tempo ho ricontrollato quello che avevo fatto, e durante un copia incolla avevo omesso :8123 nel config.jason... e per fortuna non è un problema di lentezza della rete.
Ma purtruppo mi da un altro errore, anche se ora la skill è stata comunque installata su alexa.
{
  "errorMessage": "Handler 'event_handle' missing on module 'haaska'"
}
Meanwhile, thank you very much for your interest. Time is not a problem, when I started, I immediately realized that for me it would be a long thing, in fact I checked back in what I had done, and during a copy paste I had omitted: 8123 in config.jason ... and luckily it is not a problem of slowness of the network.
But purtruppo gives me another mistake, even if now the skill was still installed on alexa.
{
   "errorMessage": "Handler 'event_handle' missing on module 'haaska'"
}
What else did I do wrong?

**Comment by anthonylavado** [comment]
In AWS Lambda, it needs to be `haaska.event_handler`, not `haaska.event_handle`.

See:
<img width="307" alt="screen shot 2019-02-28 at 1 56 51 am" src="https://user-images.githubusercontent.com/596194/53547154-44166a00-3afc-11e9-8f94-11cebe3ba2ea.png">

**Comment by pepepere** [comment]
Hi
I've the same problem... Updated to HA 88.1, I receive the error message:
{
  "errorMessage": "2019-02-28T08:53:09.634Z 8d6fecc2-19ec-49e9-a99b-6d4515748001 Task timed out after 8.01 seconds"
}

I tried with 3 and 8 secs, 
do you have any ideas? Thx for your time

**Comment by kentania** [comment]
Ok, sto facendo ogni genere di errore....
Ho ricontrollato tutto, ed ora la skill funziona, tanto che su alexa sono visibili tutti i sensori e i dispositivi già inseriti su ha , ma nonostante funzioni su aws mi da ancora un errore (ho già aggiornato a 88.2):

Ok, I'm doing all kinds of mistakes ....
I double checked everything, and now the skill works, so that on alexa are visible all the sensors and devices already inserted on ha, but despite working on aws gives me an error (I have already updated to 88.2
{
  "errorMessage": "500 Server Error: Internal Server Error for url: https://xxx.duckdns.org:8123/api/alexa/smart_home",
  "errorType": "HTTPError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      111,
      "event_handler",
      "return ha.post('alexa/smart_home', event, wait=True)"
    ],
    [
      "/var/task/haaska.py",
      66,
      "post",
      "r.raise_for_status()"
    ],
    [
      "/var/task/requests/models.py",
      940,
      "raise_for_status",
      "raise HTTPError(http_error_msg, response=self)"
    ]
  ]
}):

**Comment by anthonylavado** [comment]
When do you get this error?

**Comment by kentania** [comment]
With hassio updated 0.88.2. The skill works but on Lambda console it keeps telling me this problem if I launch the test.

**Comment by anthonylavado** [comment]
Okay. If it’s working, I think we should let this one go for now. I’m not sure why the error is happening in the test.

The test command is the exact same as if Alexa was asked to discover devices, so it really should work.

**Comment by kentania** [comment]
Mi chiedovo una cosa però ... Effettivamente alexa sta scoprendo i dispositivi, qualunque cosa io colleghi a HA la ritrovo su alexa ancora prima di fare partire la richiesta, non è che questo continuo invio di dati mi vada a superare il limite gratuito su aws e che poi mi ritrovi a dover pagare per il servizio?

I wonder one thing though ... Actually alexa is discovering the devices, whatever I connect to HA the hangout on alexa even before starting the request, it is not that this continuous sending of data I go to exceed the free limit on aws and that then you find me having to pay for the service

**Comment by anthonylavado** [comment]
After the discovery is done, Alexa only connects to HA when you say a command. The messages are very small (a few KB), and it executes quickly (1-2 seconds).

AWS Lambda provides an permanent Free Tier that allows 1M requests, allows 3,200,000 seconds of computer time, and 1 GB transfer. You should be okay :-)
