### ISSUE TITLE
How to Exclude everything and include just something

### ISSUE THREAD

**Issue by ricreis394** [mike-grant/haaska#96]
So, I have lots of entities in Home Assistant. I just need alexa to control a few entities. Is that possible to exclude every entity unless I specify which one I want to include?

**Comment by anthonylavado** [comment]
@ricreis394 This is totally possible.

In your Home Assistant configuration, it works like this:

* No include/exclude set - all items that can be controlled will appear
* Include set, no exclude - only items that are included will appear
* Include set, exclude set - same as above, only items that are included will appear
* No include set, only exclude - all devices *except* for the excluded ones, will appear

In your case, only put what you want to control in the include section. Nothing else is necessary :smile:
