### ISSUE TITLE
Humidity sensors not shown

### ISSUE THREAD

**Issue by xefil** [mike-grant/haaska#97]
Hi to all,
I was able to setup haaska and I've a looot of devices now shown. I'll try later then to filter it, but I've noticed that temperature sensors are shown, but humidity sensors not.
Is there a reason?
I.e. I've two sensors exposed via MQTT to Home Assistant, both from the same device (via MySensors). The temperature sensor is shown, humidity not. Here are the devices shown in the developer view from Home Assistant:

This is exposed:
```
entity: sensor.node30bagno_30_3
value: 20.0
battery_level: 0 
heartbeat: 0 
child_id: 3 
description: Temperatura (DS18B20) 
device: mqtt 
node_id: 30 
V_TEMP: 20.0 
unit_of_measurement: °C 
friendly_name: Bagno - Temperatura 
icon: mdi:temperature-celsius
```

This not!
```
entity: sensor.node30bagno_30_4 
value: 38.0 
battery_level: 0
heartbeat: 0 
child_id: 4 
description: Umidita' (DHT11) 
device: mqtt 
node_id: 30 
V_HUM: 38.0 
unit_of_measurement: % 
friendly_name: Bagno - Umidita' 
icon: mdi:water-percent

```
Any idea why?

Thanks!!

Simon

**Comment by anthonylavado** [comment]
Hey there @xefil! :wave: 

This is actually a limitation of the Alexa Smart Home Skill API, so it's not something that Haaska or even Home Assistant can fix.

There is the ability to handle temperature as a sensor, but not humidity. You can see a list of examples here: https://developer.amazon.com/docs/device-apis/list-of-interfaces.html

Sorry about that!

**Comment by xefil** [comment]
Oh, thank you for your **FAST** answer!
If I would like to add an Intent to let me Alexa tell me this, could I do it with the haaska setup or should I use another custom skill?
I've already a custom devel skill which answers me things if I ask:

_"Alexa, ask to MYSKILLNAME MyIntentActivator"_ (sorry, I'm using in italian, I think in english should look like this).

So, if I would like to extend this approach, which skill should I use?

Thanks, Simon

**Comment by anthonylavado** [comment]
This would be a custom item, not in Haaska. Haaska can only relay things that are supported in that list :smile:

**Comment by xefil** [comment]
Ok, then I'll implement it on the other custom skill. I've followed this guide which works (CONFIGURING YOUR AMAZON ALEXA SKILL):
https://www.home-assistant.io/components/alexa/

After that, I've implemented the smart_home part using your haaska great job.

I was thinking if I can dismiss the first skill. Seems then I can't :-)
